'use strict';
Object.assign(JJ.games,{
 colorfocus:{es:'Color contra palabra',en:'Color versus word',icon:'🎨',lower:false},
 numbertrail:{es:'Ruta del 1 al 16',en:'Trail from 1 to 16',icon:'🔢',lower:true},
 higherlower:{es:'Mayor o menor',en:'Higher or lower',icon:'↕',lower:false},
 starmap:{es:'Mapa de estrellas',en:'Star map',icon:'🌠',lower:false},
 balance:{es:'En el centro',en:'Right in the center',icon:'🎯',lower:false}
});
const arcadeGames=games;
games=async function(v){await arcadeGames(v);if(v!==state.version)return;$('#main').insertAdjacentHTML('beforeend',`<div class="section-heading"><h2>${bi('Para cualquier día del año','For any day of the year')}</h2></div><div class="extra-games">${['colorfocus','numbertrail','higherlower','starmap','balance'].map(id=>`<article class="game-panel"><div class="game-symbol">${JJ.games[id].icon}</div><h3>${bi(JJ.games[id].es,JJ.games[id].en)}</h3>${scoreTable(id,JJ.dashboard?.scores||[])}<button class="btn" data-arcade="${id}">${bi('Jugar','Play')}</button></article>`).join('')}</div>`);document.querySelectorAll('[data-arcade]').forEach(b=>b.onclick=()=>launchGame(b.dataset.arcade));};
const arcadeLaunch=launchGame;
launchGame=function(id){const fn={colorfocus:playColorFocus,numbertrail:playNumberTrail,higherlower:playHigherLower,starmap:playStarMap,balance:playBalance}[id];if(fn)fn();else arcadeLaunch(id);};
function arcadeShuffle(a){return JJPuzzles.shuffle(a,()=>Math.random());}
function playColorFocus(){const palette=[['ROJO','RED','#ff7070'],['AZUL','BLUE','#80aaff'],['VERDE','GREEN','#70dfa8'],['AMARILLO','YELLOW','#f3d269']];let score=0,ink=0,done=false,deadline=0;const v=gameSurface('colorfocus','Tienes 45 segundos, sin límite de turnos. Elige la tinta: +10 por acierto. Cada error resta 2 segundos.','You have 45 seconds with unlimited rounds. Choose the ink: +10 for each correct answer. Each mistake costs 2 seconds.',`<p id="color-count" role="timer"></p><div id="color-word" class="arcade-word"></div><div class="answer-grid">${palette.map((p,i)=>`<button class="btn secondary" data-color="${i}">${bi(p[0],p[1])}</button>`).join('')}</div>`);deadline=performance.now()+45000;const finish=()=>{if(done)return;done=true;customResult('colorfocus',score,v);};const next=()=>{ink=Math.floor(Math.random()*4);const word=Math.floor(Math.random()*4);$('#color-word').style.color=palette[ink][2];$('#color-word').innerHTML=bi(palette[word][0],palette[word][1]);};function tick(){if(done||v!==state.version)return;const left=deadline-performance.now();if(left<=0){finish();return;}$('#color-count').textContent=(left/1000).toFixed(1)+' s · '+score+' pts';jjTimer(tick,50);}document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{if(done||v!==state.version)return;if(performance.now()>=deadline){finish();return;}if(+b.dataset.color===ink)score+=10;else deadline-=2000;if(performance.now()>=deadline)finish();else next();});next();tick();}
function playNumberTrail(){let next=1,penalty=0,done=false;const order=arcadeShuffle(Array.from({length:16},(_,i)=>i+1));const v=gameSurface('numbertrail','Toca los números en orden. Cada error añade 2 segundos; gana el menor tiempo.','Tap the numbers in order. Each mistake adds 2 seconds; the lowest time wins.',`<p id="number-next"></p><div class="number-trail">${order.map(n=>`<button class="btn secondary" data-number="${n}">${n}</button>`).join('')}</div><p id="number-time"></p>`);const start=performance.now();function tick(){if(v!==state.version||done)return;$('#number-next').innerHTML=bi('Busca el','Find')+` <strong>${next}</strong>`;$('#number-time').textContent=((performance.now()-start+penalty)/1000).toFixed(1)+' s';jjTimer(tick,150);}document.querySelectorAll('[data-number]').forEach(b=>b.onclick=()=>{if(done)return;if(+b.dataset.number!==next){penalty+=2000;$('#custom-status').textContent=say('Otro número: +2 segundos','Wrong number: +2 seconds');return;}b.disabled=true;b.classList.add('found');next++;if(next===17){done=true;customResult('numbertrail',Math.min(600000,Math.max(1000,Math.round(performance.now()-start+penalty))),v);}});tick();}
function playHigherLower(){let number=Math.floor(Math.random()*100),round=0,score=0,done=false;const v=gameSurface('higherlower','¿El próximo número será mayor o menor? Los números van de 0 a 99 y nunca se repiten seguidos. 20 intentos.','Will the next number be higher or lower? Numbers range from 0 to 99 and never repeat consecutively. 20 tries.',`<p id="higher-count"></p><div class="arcade-word" id="higher-number"></div><div class="row">${jjButton('choose-lower','↓ Menor','↓ Lower','btn secondary')}${jjButton('choose-higher','↑ Mayor','↑ Higher')}</div><p id="higher-feedback" role="status"></p>`);const render=()=>{$('#higher-number').textContent=number;$('#higher-count').textContent=`${round+1} / 20 · ${score} pts`;};const choose=higher=>{if(done)return;let value=Math.floor(Math.random()*99);if(value>=number)value++;const correct=(value>number)===higher;$('#higher-feedback').textContent=`${number} → ${value} · ${correct?say('¡Acertaste!','Correct!'):say('Esta vez no','Not this time')}`;if(correct)score+=10;number=value;if(++round===20){done=true;customResult('higherlower',score,v);}else render();};$('#choose-lower').onclick=()=>choose(false);$('#choose-higher').onclick=()=>choose(true);render();}
function playStarMap(){let round=0,score=0,targets=[],chosen=new Set(),accepting=false,done=false,deadline=0;const v=gameSurface('starmap','Recuerda las estrellas. Observa menos de un segundo y responde antes de que termine el contador. Cada ronda es más rápida, sin límite de turnos.','Remember the stars. Watch for less than a second and answer before the countdown ends. Each round gets faster, with unlimited rounds.',`${jjButton('stars-start','Observar','Watch')}<p id="stars-note"></p><p id="stars-clock" role="timer"></p><div class="star-map">${Array.from({length:16},(_,i)=>`<button disabled data-star="${i}" aria-label="${say('Casilla','Tile')} ${i+1}">·</button>`).join('')}</div>`);const buttons=[...document.querySelectorAll('[data-star]')];const finish=()=>{if(done)return;done=true;accepting=false;customResult('starmap',score,v);};function tick(){if(done||v!==state.version||!accepting)return;const left=deadline-performance.now();if(left<=0){finish();return;}$('#stars-clock').textContent=(left/1000).toFixed(1)+' s · '+score+' pts';jjTimer(tick,50);}const next=()=>{if(done||v!==state.version)return;accepting=false;chosen=new Set();targets=arcadeShuffle(Array.from({length:16},(_,i)=>i)).slice(0,Math.min(8,2+Math.floor(round/3)));$('#stars-note').innerHTML=bi('Observa la constelación','Watch the constellation')+` · ${round+1}`;$('#stars-clock').textContent=score+' pts';buttons.forEach((b,i)=>{b.disabled=true;b.textContent=targets.includes(i)?'⭐':'·';b.classList.remove('found');});jjTimer(()=>{if(done||v!==state.version)return;buttons.forEach(b=>{b.textContent='·';b.disabled=false;});accepting=true;deadline=performance.now()+Math.max(1500,4000-round*150);$('#stars-note').innerHTML=bi('¡Encuéntralas antes de que se acabe el tiempo!','Find them before time runs out!');tick();},Math.max(350,900-round*40));};buttons.forEach((b,i)=>b.onclick=()=>{if(!accepting||done||v!==state.version||chosen.has(i))return;if(performance.now()>=deadline||!targets.includes(i)){finish();return;}chosen.add(i);b.textContent='⭐';b.disabled=true;b.classList.add('found');if(chosen.size===targets.length){accepting=false;score+=10;round++;jjTimer(next,350);}});$('#stars-start').onclick=()=>{$('#stars-start').remove();next();};}
function playBalance(){let round=0,score=0,start=0,running=false,phase=0;const v=gameSurface('balance','Detén el punto lo más cerca posible del centro. 10 intentos; cada ronda es más rápida.','Stop the dot as close to the center as possible. 10 tries; each round gets faster.',`<p id="balance-count"></p><div class="balance-track"><div class="balance-center"></div><span id="balance-dot"></span></div>${jjButton('balance-stop','Comenzar','Start')}<p id="balance-feedback" role="status"></p>`);const position=()=>50+48*Math.sin((performance.now()-start)*(0.002+round*0.0003)+phase);function frame(){if(v!==state.version)return;if(running)$('#balance-dot').style.left=position()+'%';jjTimer(frame,25);}const begin=()=>{phase=Math.random()*Math.PI*2;start=performance.now();running=true;$('#balance-count').textContent=`${round+1} / 10 · ${score} pts`;$('#balance-stop').innerHTML=bi('¡Detener!','Stop!');};$('#balance-stop').onclick=()=>{if(!running){begin();return;}running=false;const points=Math.round(Math.max(0,100-Math.abs(position()-50)*2));score+=points;round++;$('#balance-feedback').textContent=`+${points} pts`;if(round===10)customResult('balance',score,v);else $('#balance-stop').innerHTML=bi('Siguiente intento','Next try');};frame();}
