'use strict';
const ComicReader={
 fields(g){const x=g.experience||{};return `<fieldset><legend>${bi('Nuestro primer capítulo · 4 páginas','Our first chapter · 4 pages')}</legend><p>${bi('Sube las imágenes en el orden de lectura. Se mostrarán una debajo de otra. Máximo 50 MB por imagen.','Upload the images in reading order. They will appear vertically. Up to 50 MB per image.')}</p>${[1,2,3,4].map(i=>`<label>${bi('Página ','Page ')}${i}${x['page'+i]?bi(' · guardada ✓',' · saved ✓'):''}<input type="file" name="comic${i}" accept="image/jpeg,image/png,image/webp"></label>`).join('')}</fieldset>`;},
 async collect(g,form,uid){const x={...(g.experience||{})};for(let i=1;i<=4;i++){const f=form.elements['comic'+i]?.files[0];if(!f)continue;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>50*1024*1024)throw Error(say('Usa JPG, PNG o WebP de hasta 50 MB.','Use JPG, PNG or WebP up to 50 MB.'));const path=uid+'/'+crypto.randomUUID();const {error}=await db.storage.from('jj-gifts').upload(path,f,{contentType:f.type,upsert:false});if(error)throw error;x['page'+i]=path;}if(form.elements.ready.checked&&Object.keys(x).some(k=>/^page[1-4]$/.test(k))&&[1,2,3,4].some(i=>!x['page'+i]))throw Error(say('Sube las cuatro páginas antes de marcar el regalo listo.','Upload all four pages before marking the gift ready.'));return x;},
 async mount(g,generation,{owner,visited,claimed,send}){
  const root=document.createElement('section');root.className='comic-reader';$('#gift-media').append(root);const current=()=>generation===modalVersion&&root.isConnected;const seen=new Set(visited);const claim=$('#gift-claim');const status=document.createElement('p');status.className='comic-progress';status.setAttribute('role','status');root.append(status);const refresh=()=>{status.textContent=say('Páginas recorridas: ','Pages read: ')+seen.size+'/4';if(claim)claim.disabled=!claimed&&seen.size<4;};refresh();
  let observer;const pending=new Set();const mark=async page=>{if(owner||seen.has(page)||pending.has(page)||!current())return;pending.add(page);try{if(await send(page)&&current()){seen.add(page);refresh();}}finally{pending.delete(page);}};
  observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)mark(+e.target.dataset.comicEnd);},{root:$('#modal'),threshold:1});
  $('#modal').addEventListener('close',()=>observer.disconnect(),{once:true});JJ.cleanups.push(()=>observer.disconnect());
  for(let i=1;i<=4;i++){if(!current())break;const article=document.createElement('article');article.innerHTML=`<h3>${bi('Página ','Page ')}${i} / 4</h3>`;root.append(article);try{if(!g.experience['page'+i])throw Error('EMPTY_PAGE');const {data,error}=await db.storage.from('jj-gifts').createSignedUrl(g.experience['page'+i],3600);if(error)throw error;if(!current())break;const img=document.createElement('img');img.alt=say('Página del cómic ','Comic page ')+i;img.src=data.signedUrl;article.append(img);await img.decode();if(!current())break;const end=document.createElement('div');end.className='comic-end';end.dataset.comicEnd=i;end.textContent=say('Fin de la página ','End of page ')+i;article.append(end);observer.observe(end);}catch{if(!current())break;const retry=document.createElement('p');retry.textContent=say('No se pudo cargar esta página. Cierra y vuelve a abrir el regalo.','Could not load this page. Close and reopen the gift.');article.append(retry);}}
 }
};
