'use strict';
const JJ = {
  dashboard:null, season:'halloween', settings:'halloween', cleanups:[], demoPlaylists:[],
  games:{
    memory:{es:'Memoria de corazones',en:'Memory of hearts',icon:'♡',lower:false},
    reaction:{es:'Un latido veloz',en:'A quick heartbeat',icon:'⚡',lower:true},
    pumpkins:{es:'Caza calabazas',en:'Pumpkin hunt',icon:'🎃',lower:false},
    sequence:{es:'Eco embrujado',en:'Haunted echo',icon:'🔮',lower:false},
    arithmetic:{es:'Pociones matemáticas',en:'Math potions',icon:'🧪',lower:false},
    typing:{es:'Hechizo escrito',en:'Typing spell',icon:'📜',lower:true},
    pairs:{es:'Parejas monstruosas',en:'Monster pairs',icon:'🧟',lower:true},
    lights:{es:'Luces del castillo',en:'Castle lights',icon:'🏰',lower:false},
    wordsearch:{es:'Sopa de letras',en:'Word search',icon:'🔎',lower:true},
    maze:{es:'Laberinto',en:'Maze',icon:'🌀',lower:true}
  }
};
function bi(es,en){return `<span translate="no"><span class="lang-es">${es}</span><span class="lang-en">${en}</span></span>`;}
function say(es,en){return UniverseI18n.language==='en'?en:es;}
function jjButton(id,es,en,style='btn'){return `<button id="${id}" class="${style}">${bi(es,en)}</button>`;}
function jjError(error){console.error(error);toast(say('No se pudo completar. Revisa tu conexión y la guía de actualización v5.','Could not complete. Check your connection and the v5 update guide.'));}
async function rpc(name,args={}){const {data,error}=await db.rpc(name,args);if(error)throw error;return data;}
function jjCleanup(){JJ.cleanups.splice(0).forEach(fn=>fn());}
function jjTimer(fn,delay){return later(fn,delay);}
function jjDate(value){return new Date(String(value).slice(0,10)+'T12:00:00').toLocaleDateString(UniverseI18n.locale(),{month:'short',day:'numeric'});}
function demoDashboard(){const today=new Date();const monday=new Date(today.getFullYear(),today.getMonth(),today.getDate()-(today.getDay()+6)%7);const endWeek=new Date(monday);endWeek.setDate(endWeek.getDate()+7);const day=Date.UTC(today.getFullYear(),today.getMonth(),today.getDate());const anchor=Date.UTC(2026,8,28);const endPeriod=new Date(anchor+(Math.floor((day-anchor)/1209600000)+1)*1209600000);const scores=Object.keys(JJ.games).flatMap(game=>(demoScores[game]||[]).map(r=>({user_id:'demo-'+r.handle,game,best:r.best,profiles:{handle:r.handle,display_name:r.handle==='julisa'?'Julissa':'Jesús'}})));return {coins:0,week_end:[endWeek.getFullYear(),String(endWeek.getMonth()+1).padStart(2,'0'),String(endWeek.getDate()).padStart(2,'0')].join('-'),period_end:endPeriod.toISOString().slice(0,10),scores,missions:missionDefinitions.map(([id,,,target])=>({id,progress:0,target,claimed:false})),crowns:[{handle:'julisa',name:'Julissa',total:0,wears:false},{handle:'jesus',name:'Jesús',total:0,wears:false}]};}
async function getDashboard(){JJ.dashboard=state.demo?demoDashboard():await rpc('jj_dashboard');return JJ.dashboard;}
function currentTheme(mode){if(mode!=='auto')return JJ_SEASONS.designs[mode]?mode:'classic';const d=new Date();const stamp=String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');return JJ_SEASONS.calendar.find(x=>stamp>=x.from&&stamp<=x.to)?.design||'classic';}
function applySeason(mode){JJ.settings=mode;JJ.season=currentTheme(mode);document.documentElement.dataset.season=JJ.season;try{localStorage.setItem('jj-season',mode);}catch{}}
try{applySeason(localStorage.getItem('jj-season')||JJ_SEASONS.default);}catch{applySeason(JJ_SEASONS.default);}
async function loadSeason(){if(!state.demo&&db){const {data,error}=await db.from('app_settings').select('season').eq('id',1).single();if(error)throw error;applySeason(data.season);}}
function seasonRibbon(){const design=JJ_SEASONS.designs[JJ.season];return `<div class="season-ribbon" aria-hidden="true"><span>${design.symbols}</span><img src="${design.image}" alt=""><span>J & J</span></div>`;}
function crownTable(data){return `<div class="crown-board"><div><div class="eyebrow">${bi('Nuestro salón de coronas','Our crown hall')}</div><h2>${bi('Dos nombres. Muchas aventuras.','Two names. So many adventures.')}</h2></div><div class="crown-people">${[...data.crowns].sort((a,b)=>b.total-a.total).map(p=>`<div><span class="avatar ${p.handle}">${p.name[0]}</span><strong>${esc(p.name)} ${p.wears?'👑':''}</strong><span>${p.total} ${bi('coronas','crowns')}</span></div>`).join('')}</div><p class="hint">${bi('La corona cambia cada 14 días. Próximo cierre:','The crown changes every 14 days. Next closing:')} ${jjDate(data.period_end)} · ${bi('Empate exacto: corona para ambos.','Exact tie: a crown for both.')}</p></div>`;}
function scoreTable(game,rows){const meta=JJ.games[game];const sorted=Object.entries(names).map(([handle,name])=>({name,score:rows.find(x=>x.game===game&&x.profiles.handle===handle)?.best})).sort((a,b)=>a.score==null?b.score==null?0:1:b.score==null?-1:meta.lower?a.score-b.score:b.score-a.score);return `<table class="leaderboard"><thead><tr><th>${bi('Lugar','Place')}</th><th>${bi('Jugador','Player')}</th><th>${bi('Récord','Best')}</th></tr></thead><tbody>${sorted.map((r,i)=>`<tr><td>${r.score==null?'—':i===1&&r.score===sorted[0].score?'1 =':i+1}</td><td>${esc(r.name)}</td><td>${r.score==null?bi('Por jugar','Not played'):meta.lower?(r.score/1000).toFixed(2)+' s':r.score+' pts'}</td></tr>`).join('')}</tbody></table>`;}
const oldGameScores=gameScores;
gameScores=async()=>{const data=await getDashboard();return Object.fromEntries(Object.keys(JJ.games).map(game=>[game,data.scores.filter(r=>r.game===game)]));};
const oldSaveScore=saveScore;
saveScore=async(game,score,attempt=crypto.randomUUID())=>{if(state.demo){demoScores[game]??=[];const old=demoScores[game].find(x=>x.handle===state.profile.handle);if(old)old.best=JJ.games[game].lower?Math.min(old.best,score):Math.max(old.best,score);else demoScores[game].push({handle:state.profile.handle,best:score});return;}await rpc('record_game_once',{p_game:game,p_score:score,p_attempt:attempt});};

menus.splice(3,0,['playlists','♫','Playlists']);
menus.push(['puzzles','⌘','Game'],['truth','♠','Verdad o reto'],['missions','✦','Misiones JJ'],['season','☾','Temporadas']);
const originalNavigate=navigate;
navigate=async function(page){jjCleanup();let navigationVersion;try{
  if(['playlists','puzzles','truth','missions','season'].includes(page)){
    if(!state.profile)return;clearTimers();state.page=page;const v=++state.version;navigationVersion=v;shell();window.scrollTo(0,0);$('#main').innerHTML='<p class="loading">'+bi('Preparando nuestro universo…','Getting our universe ready…')+'</p>';
    await loadSeason();if(v!==state.version)return;
    const routes={playlists:playlistPage,puzzles:puzzlePage,truth:truthPage,missions:missionPage,season:seasonPage};await routes[page](v);
  }else{const pending=originalNavigate(page);navigationVersion=state.version;await pending;if(state.page!==page||navigationVersion!==state.version)return;await loadSeason();}
  if(navigationVersion!==state.version)return;
  if(state.profile){
    const v=state.version;const d=await getDashboard();if(v!==state.version)return;
    $('#main')?.insertAdjacentHTML('afterbegin',seasonRibbon());
    const profileBox=$('.sidebar-bottom strong');const c=d.crowns.find(x=>x.handle===state.profile.handle);if(profileBox&&c?.wears)profileBox.append(' 👑');if(c?.wears&&$('.welcome em'))$('.welcome em').append(' 👑');
    if($('.sidebar-bottom'))$('.sidebar-bottom').insertAdjacentHTML('afterbegin',`<div class="coin-pill">✦ ${d.coins} JJ</div>`);
    if(page==='home'){$('#main').insertAdjacentHTML('beforeend',crownTable(d));decorateHome();}
  }
}catch(error){if(state.profile&&state.page===page&&navigationVersion===state.version){$('#main').innerHTML=`<div class="empty"><h2>${bi('Falta conectar la actualización','Connect the update')}</h2><p>${bi('Revisa ACTUALIZAR-VIDA-COMPARTIDA.md y aplica las actualizaciones que te falten. No repitas archivos antiguos ni borres tablas.','Check ACTUALIZAR-VIDA-COMPARTIDA.md and apply any missing updates. Do not rerun old files or delete tables.')}</p>${jjButton('jj-retry','Reintentar','Try again')}</div>`;$('#jj-retry').onclick=()=>navigate(page);}console.error(error);}};
const originalLogout=logout;logout=async()=>{jjCleanup();return originalLogout();};
function decorateHome(){if(JJ.season==='classic'){const hero=$('.hero');if(hero){hero.innerHTML=`<img class="hero-photo" src="assets/our-hands.jpg" alt="Julissa y Jesús tomados de las manos"><div class="hero-content"><div class="eyebrow">JULISSA & JESÚS</div><h1>${bi('De tu mano,<br><em>todo es hogar.</em>','Holding your hand,<br><em>anywhere is home.</em>')}</h1><p>${bi('Nuestro lugar para guardar lo que somos.','Our place to keep the moments that make us, us.')}</p>${jjButton('our-memories','Nuestros recuerdos','Our memories')}</div>`;$('#our-memories').onclick=()=>navigate('memories');}return;}if(JJ.season!=='halloween')return;const hero=$('.hero');if(hero){hero.innerHTML=`<img class="hero-photo halloween-hero" src="assets/halloween-couple.png" alt="Julissa y Jesús de Halloween"><div class="hero-content"><div class="eyebrow">${bi('Una temporada para nosotros','A season for us')}</div><h1>${bi('Mi susto favorito<br><em>es enamorarme de ti.</em>','My favorite thrill?<br><em>Falling for you.</em>')}</h1><p>${bi('Calabazas, canciones y un castillo lleno de momentos juntos.','Pumpkins, songs and a castle full of moments together.')}</p>${jjButton('haunted-play','Vamos a jugar 🎃','Let’s play 🎃')}</div>`;$('#haunted-play').onclick=()=>navigate('games');}}
async function seasonPage(){const isOwner=state.profile.handle==='jesus';$('#main').innerHTML=`<div class="page-heading"><div class="eyebrow">J & J</div><h1>${bi('Un universo, muchas temporadas','One universe, many seasons')}</h1><p>${bi('Conservamos cada decoración para volver a vivirla.','Every decoration is kept so we can enjoy it again.')}</p></div><div class="season-options">${Object.entries(JJ_SEASONS.designs).map(([id,s])=>`<article class="media-card"><img src="${s.image}" alt=""><div class="card-body"><h3>${bi(s.es,s.en)}</h3><button class="btn secondary" data-season="${id}" ${!isOwner?'disabled':''}>${bi('Usar esta temporada','Use this season')}</button></div></article>`).join('')}</div><p style="margin:24px 0">${bi('Automático: flores del 15 al 25 de septiembre; Halloween del 26 de septiembre al 31 de octubre. Se repite cada año.','Automatic: flowers September 15–25; Halloween September 26–October 31. Repeats every year.')}</p><button class="btn" data-season="auto" ${!isOwner?'disabled':''}>${bi('Activar calendario anual','Use the yearly calendar')}</button><p class="hint" style="margin-top:16px">${bi('Jesús puede cambiar la temporada para los dos. Navidad podrá añadirse después a este catálogo.','Jesús can change the season for both of you. Christmas can be added to this catalog later.')}</p><p id="season-state" role="status"></p>`;document.querySelectorAll('button[data-season]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{if(!state.demo){const {error}=await db.from('app_settings').update({season:b.dataset.season,updated_at:new Date().toISOString()}).eq('id',1);if(error)throw error;}applySeason(b.dataset.season);toast(say('Temporada actualizada','Season updated'));await navigate('season');}catch(e){jjError(e);b.disabled=false;}});}

const missionDefinitions=[
 ['visit','Entrar a nuestro universo','Visit our universe',1],['letter','Escribir una cartita','Write a letter',1],['letters3','Enviar tres cartitas','Send three letters',3],['photo','Guardar un recuerdo','Save a memory',1],['song','Subir una canción','Upload a song',1],['comment','Dejar un comentario','Leave a comment',1],['playlist','Crear una playlist','Create a playlist',1],['game1','Completar un juego','Finish a game',1],['games3','Completar tres partidas','Finish three rounds',3],['variety','Jugar tres juegos diferentes','Play three different games',3],['leader','Llegar al primer lugar','Reach first place',1],['improve','Superar tu propio récord','Beat your own record',1],['puzzle','Resolver una sopa o laberinto','Solve a word search or maze',1],['together','Completar una tarjeta juntos','Complete a card together',1]
];
async function missionPage(v){const data=await getDashboard();if(v!==state.version)return;$('#main').innerHTML=`<div class="page-heading"><div class="eyebrow">${bi('Pequeños pasos, historias grandes','Little steps, big stories')}</div><h1>${bi('Nuestras misiones','Our missions')}</h1><p>${bi('14 misiones semanales. Cada misión completada suma 1 moneda JJ, una sola vez.','14 weekly missions. Each completed mission earns 1 JJ coin, once.')}</p></div><div class="mission-summary"><strong>✦ ${data.coins} JJ</strong><p>${bi('Tus monedas se acumulan. Por ahora no se gastan.','Your coins add up. For now, they cannot be spent.')}<br>${bi('Nueva semana:','Next week:')} ${jjDate(data.week_end)}</p></div><div class="mission-grid">${missionDefinitions.map(([id,es,en])=>{const m=data.missions.find(x=>x.id===id);return `<article class="mission ${m.claimed?'complete':''}"><span>${m.claimed?'✓':'✧'}</span><div><h3>${bi(es,en)}</h3><progress max="${m.target}" value="${Math.min(m.progress,m.target)}"></progress><p>${Math.min(m.progress,m.target)} / ${m.target} · +1 JJ</p></div></article>`;}).join('')}</div><p class="hint" style="margin-top:24px">${bi('Los horarios siguen America/Matamoros. Los lunes se renuevan las misiones; el saldo JJ permanece.','Schedules use America/Matamoros. Missions renew on Mondays; your JJ balance stays.')}</p>`;}
