'use strict';
const CONTENT={posts:new Map(),translations:new Map(),working:false,queued:false};
canDeleteMusic=()=>false;
confirmDeleteMusic=p=>deletionDialog('post',p);
const lifePostCard=postCard;
postCard=function(p){CONTENT.posts.set(p.id,p);const html=lifePostCard(p).replace('<h3 translate="no">',`<h3 translate="no" data-post-text="${p.id}" data-field="title">`).replace('<p translate="no">',`<p translate="no" data-post-text="${p.id}" data-field="body" data-short="true">`);return html.replace('</article>',`<div class="card-body post-controls">${p.author_id===state.profile.id?`<button class="text-button" data-edit-post="${p.id}">${bi('Editar','Edit')}</button>`:''}<button class="text-button" data-request-post="${p.id}">${bi('Solicitar eliminación','Request deletion')}</button><span class="translation-note" data-translation-note="${p.id}"></span></div></article>`);};
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-post]'),del=e.target.closest('[data-request-post]');if(edit)editPostForm(CONTENT.posts.get(edit.dataset.editPost));if(del)deletionDialog('post',CONTENT.posts.get(del.dataset.requestPost));});
const lifeOpenPost=openPost;
openPost=async function(p){CONTENT.posts.set(p.id,p);const promise=lifeOpenPost(p);const root=$('#modal-body');const title=$('h2[translate=no]',root),body=$('p[translate=no]',root);if(title){title.dataset.postText=p.id;title.dataset.field='title';}if(body){body.dataset.postText=p.id;body.dataset.field='body';body.insertAdjacentHTML('afterend',`<p class="translation-note" data-translation-note="${p.id}"></p>`);}await promise;queueTranslations();};
const lifePlaylistPage=playlistPage;
playlistPage=async function(v){await lifePlaylistPage(v);if(v!==state.version)return;document.querySelectorAll('[data-listen]').forEach(b=>{const del=document.createElement('button');del.className='text-button';del.innerHTML=bi('Solicitar eliminación','Request deletion');b.parentElement.append(del);del.onclick=async()=>{try{const {data,error}=await db.from('playlists').select('*').eq('id',b.dataset.listen).single();if(error)throw error;await deletionDialog('playlist',data);}catch(e){lifeError(e);}};});};
function editPostForm(p){if(!p||p.author_id!==state.profile.id)return;publicationForm(p.kind,p);}
postForm=kind=>publicationForm(kind);
function publicationForm(kind,p){const id=p?.id||crypto.randomUUID();let image=p?.image_path||null,audio=p?.audio_path||null;let uploadedImage=null,uploadedAudio=null;let soundtrack=p?.memory_song_id?{source:'local',id:p.memory_song_id,title:say('Canción de Nuestra música','Song from Our music')}:p?.spotify_track?{source:'spotify',id:p.spotify_track,title:'Spotify'}:null;
 modal(`<h2>${bi(p?'Editar publicación':pageInfo[kind][3],p?'Edit post':kind==='music'?'Upload a song':kind==='memories'?'Save a memory':'Write a letter')}</h2><form id="post-form" class="stack"><label>${bi('Título','Title')}<input name="title" maxlength="120" required value="${esc(p?.title||'')}"></label><label>${bi(kind==='music'?'La historia de esta canción':'Tus palabras',kind==='music'?'The story of this song':'Your words')}<textarea name="body" maxlength="5000" ${kind==='messages'?'required':''}>${esc(p?.body||'')}</textarea></label><label>${bi('Idioma en el que estás escribiendo','Language you are writing in')}<select name="language" translate="no"><option value="es" ${(p?.source_lang||UniverseI18n.language)==='es'?'selected':''}>Español</option><option value="en" ${(p?.source_lang||UniverseI18n.language)==='en'?'selected':''}>English</option></select></label><label>${bi(p?'Cambiar imagen (opcional)':'Imagen',p?'Replace image (optional)':'Image')} · 10 MB<input type="file" name="image" accept="image/jpeg,image/png,image/webp,image/gif" ${kind==='memories'&&!p?'required':''}></label>${kind!=='memories'&&p?.image_path?`<label class="row"><input type="checkbox" name="remove-image">${bi('Quitar imagen actual','Remove current image')}</label>`:''}${kind==='music'?`<label>${bi(p?'Cambiar audio (opcional)':'Audio',p?'Replace audio (optional)':'Audio')} · 25 MB<input type="file" name="audio" accept="audio/mpeg,audio/mp4,audio/wav,audio/x-wav,audio/ogg,audio/flac,audio/x-m4a" ${!p?'required':''}></label>`:''}<p class="hint">${bi('Se conserva el texto original. Al cambiar de idioma, la traducción gratuita envía el texto a MyMemory; puedes desactivarla en Perfiles.','The original text is preserved. Switching languages uses free translation by sending the text to MyMemory; you can turn this off in Profiles.')}</p>${kind==='memories'?`<section class="memory-music"><h3>${bi('Música de este recuerdo','Music for this memory')}</h3><p id="memory-track" translate="no"></p><button type="button" id="remove-memory-track" class="text-button">${bi('Sin música','No music')}</button><div id="memory-picker"></div></section>`:''}<p class="error" id="form-error"></p><button class="btn">${bi('Guardar con cariño','Save with love')}</button></form>`);
 if(kind==='memories'){const renderTrack=()=>{$('#memory-track').textContent=soundtrack?.title||say('Sin música','No music');};renderTrack();$('#remove-memory-track').onclick=()=>{soundtrack=null;renderTrack();};mountMusicPicker($('#memory-picker'),track=>{soundtrack=track;renderTrack();});}
 $('#post-form').onsubmit=async e=>{e.preventDefault();if(!ensureLive())return;const f=new FormData(e.target),btn=$('button:not([type=button])',e.target);btn.disabled=true;busyModal(true);try{if(!p){const check=await db.from('posts').select('id').eq('id',id).maybeSingle();if(check.error)throw check.error;if(check.data){$('#modal').close();if(kind==='messages')state.messageTab='sent';await navigate(kind);return;}}
 const img=f.get('image'),aud=f.get('audio');if(img?.size&&uploadedImage!==img){image=await upload(img,'image',[]);uploadedImage=img;}else if(f.has('remove-image')&&!img?.size)image=null;if(aud?.size&&uploadedAudio!==aud){audio=await upload(aud,'audio',[]);uploadedAudio=aud;}
 if(p)await rpc('jj_edit_post_v7',{p_id:id,p_revision:p.revision,p_title:f.get('title'),p_body:f.get('body'),p_image:image,p_audio:audio,p_lang:f.get('language'),p_song:soundtrack?.source==='local'?soundtrack.id:null,p_spotify:soundtrack?.source==='spotify'?soundtrack.id:null});else{const {error}=await db.from('posts').insert({id,author_id:state.profile.id,kind,title:f.get('title').trim(),body:f.get('body').trim(),image_path:image,audio_path:audio,source_lang:f.get('language'),memory_song_id:soundtrack?.source==='local'?soundtrack.id:null,spotify_track:soundtrack?.source==='spotify'?soundtrack.id:null});if(error)throw error;}
 $('#modal').close();if(kind==='messages')state.messageTab='sent';await navigate(kind);toast(say('Guardado con cariño','Saved with love'));
 }catch(err){$('#form-error').textContent=say('No se pudo confirmar el guardado. Tu texto sigue aquí. Si estabas editando, abre la publicación en otra pestaña para comprobar si ya cambió antes de reintentar.','Could not confirm the save. Your text is still here. If editing, open the post in another tab to check whether it changed before retrying.');}finally{busyModal(false);btn.disabled=false;}};
}
// Split at UTF-8 byte boundaries, preserving whitespace and emoji.
function translationChunks(text,max=450){const enc=new TextEncoder(),chunks=[];let remaining=text;while(remaining){let count=0,end=0,boundary=0;for(const char of remaining){const size=enc.encode(char).length;if(count+size>max)break;count+=size;end+=char.length;if(/\s/.test(char))boundary=end;}if(!end)throw Error('Chunk too small');if(end<remaining.length&&boundary>0)end=boundary;chunks.push(remaining.slice(0,end));remaining=remaining.slice(end);}return chunks;}
async function freeTranslate(text,source,target,store=null){if(!text.trim())return text;const parts=[];for(const [index,chunk] of translationChunks(text).entries()){const saved=store?.get(index);if(saved!==undefined){parts.push(saved);continue;}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const url=new URL('https://api.mymemory.translated.net/get');url.searchParams.set('q',chunk);url.searchParams.set('langpair',`${source}|${target}`);const response=await fetch(url,{signal:controller.signal,referrerPolicy:'no-referrer',credentials:'omit'});if(!response.ok)throw Error('Translation service unavailable');const data=await response.json();if(Number(data.responseStatus)!==200||data.quotaFinished||!data.responseData?.translatedText)throw Error('Translation daily limit or service error');const lead=chunk.match(/^\s*/)[0],tail=chunk.match(/\s*$/)[0];const translated=lead+data.responseData.translatedText.trim()+tail;if(store)await store.set(index,translated);parts.push(translated);}finally{clearTimeout(timer);}}return parts.join('');}
function renderPostText(p,target,translation,status){for(const el of document.querySelectorAll(`[data-post-text="${p.id}"]`)){const value=translation?.[el.dataset.field]??p[el.dataset.field];el.textContent=el.dataset.short&&value.length>180?value.slice(0,180)+'…':value;}for(const el of document.querySelectorAll(`[data-translation-note="${p.id}"]`)){el.textContent=status==='original'?'':status==='ready'?say('Traducción automática · original conservado','Automatic translation · original preserved'):status==='loading'?say('Traduciendo…','Translating…'):status==='off'?say('Texto original · traducción desactivada','Original text · translation off'):say('Original · traducción no disponible por ahora. Actualiza para reintentar.','Original · translation unavailable right now. Refresh to retry.');el.classList.toggle('translation-failed',status==='error');}}
async function translateVisiblePosts(){if(CONTENT.working){CONTENT.queued=true;return;}CONTENT.working=true;const target=UniverseI18n.language,user=state.profile?.id;try{const ids=[...new Set([...document.querySelectorAll('[data-post-text]')].map(el=>el.dataset.postText))];for(const id of ids){if(UniverseI18n.language!==target||state.profile?.id!==user)break;const p=CONTENT.posts.get(id);if(!p)continue;const source=p.source_lang||(p.profiles?.handle==='julisa'?'en':'es');if(source===target){renderPostText(p,target,null,'original');continue;}if(localStorage.getItem('jj-translate')==='off'){renderPostText(p,target,null,'off');continue;}const key=`${id}:${p.revision}:${target}`;let translated=CONTENT.translations.get(key);if(translated){renderPostText(p,target,translated,'ready');continue;}renderPostText(p,target,null,'loading');try{const cached=await db.from('post_translations').select('title,body').eq('post_id',id).eq('revision',p.revision).eq('target_lang',target).maybeSingle();if(cached.error)throw cached.error;translated=cached.data;if(!translated){const segmentResult=await db.from('translation_segments').select('*').eq('post_id',id).eq('revision',p.revision).eq('target_lang',target);if(segmentResult.error)throw segmentResult.error;const segmentStore=field=>({get:index=>segmentResult.data.find(x=>x.field===field&&x.part===index)?.content,set:(index,text)=>rpc('jj_translation_segment',{p_id:id,p_revision:p.revision,p_target:target,p_field:field,p_part:index,p_content:text})});translated={title:await freeTranslate(p.title,source,target,segmentStore('title')),body:await freeTranslate(p.body,source,target,segmentStore('body'))};await rpc('jj_translation',{p_id:id,p_revision:p.revision,p_target:target,p_title:translated.title,p_body:translated.body});}CONTENT.translations.set(key,translated);if(target===UniverseI18n.language&&state.profile?.id===user)renderPostText(p,target,translated,'ready');}catch(e){if(target===UniverseI18n.language&&state.profile?.id===user)renderPostText(p,target,null,'error');console.warn('Translation unavailable',e);}}}finally{CONTENT.working=false;if(CONTENT.queued){CONTENT.queued=false;queueTranslations();}}}
let contentTranslateTimer;
function queueTranslations(){clearTimeout(contentTranslateTimer);contentTranslateTimer=setTimeout(translateVisiblePosts,120);}
new MutationObserver(records=>{if(records.some(r=>[...r.addedNodes].some(n=>n.nodeType===1&&(n.matches?.('[data-post-text]')||n.querySelector?.('[data-post-text]')))))queueTranslations();}).observe(document.body,{childList:true,subtree:true});
window.addEventListener('universe-language',queueTranslations);
const contentLogout=logout;logout=async()=>{CONTENT.posts.clear();CONTENT.translations.clear();return contentLogout();};
