'use strict';
JJ.games.wands={es:'Duelo de varitas',en:'Wand duel',icon:'🪄',lower:false};
const ghostNames=[['Poltergeist','Poltergeist'],['Banshee','Banshee'],['Eco residual','Residual echo'],['Fuego fatuo','Will-o’-the-wisp']];
const arrowSymbols=['↑','←','↓','→'];
function wandBeatDuration(i){return Math.max(500,1200-Math.floor(i/4)*70);}
function wandBeatStart(i){let ms=0;for(let n=0;n<i;n++)ms+=wandBeatDuration(n);return ms;}
function wandBeatAt(ms){if(ms<0)return -1;let elapsed=0;for(let i=0;i<240;i++){elapsed+=wandBeatDuration(i);if(ms<elapsed)return i;}return 240;}
const eventsFlowers=flowers;
flowers=async function(v){await loadSeason();if(v!==state.version)return;if(JJ.season==='september'){await eventsFlowers(v);return;}if(JJ.season==='halloween'){await duoPage('ghost',v);return;}$('#main').innerHTML=lifeHeading('Eventos de nuestro universo','Events in our universe','Cada temporada tiene una sorpresa para los dos.','Every season has a surprise for both of you.')+`<div class="empty"><span class="symbol">✦</span><h2>${bi('La próxima sorpresa está por llegar','The next surprise is on its way')}</h2><p>${bi('Flores en septiembre y misterios en Halloween. Puedes elegir la temporada desde su menú.','Flowers in September and mysteries at Halloween. You can choose the season in its menu.')}</p></div>`;};
const wandPuzzlePage=puzzlePage;
puzzlePage=async function(v){await wandPuzzlePage(v);if(v!==state.version)return;$('#main').insertAdjacentHTML('beforeend',`<section class="game-panel" style="margin-top:24px"><div class="eyebrow">${bi('Dos jugadores · en vivo','Two players · live')}</div><h2>🪄 ${bi('Duelo de varitas','Wand duel')}</h2><p>${bi('El ritmo acelera. Al tercer error pierdes; cada partida terminada da 1 JJ a ambos.','The rhythm speeds up. Three mistakes lose the duel; every completed round earns both players 1 JJ.')}</p><div id="wand-ranking">${tttRanking((JJ.dashboard?.scores||[]).filter(r=>r.game==='wands'))}</div>${jjButton('open-wands','Entrar al duelo','Enter duel')}</section>`);$('#open-wands').onclick=()=>{jjCleanup();clearTimers();const version=++state.version;duoPage('wands',version).catch(lifeError);};};
async function duoPage(kind,v){
 const ghost=kind==='ghost',session=crypto.randomUUID();let data=null,joined=false,busy=false,stopped=false,polling=false,offset=0,lastRound=null,sent=new Set(),error='',lastRender='',lastBeat=-99;
 const scenes=[['La lluvia acompaña su investigación.','Rain accompanies your investigation.'],['Todo empezó con una carta sin firma.','It all started with an unsigned letter.'],['Alguien dejó un aviso escrito a mano.','Someone left a handwritten warning.'],['El reloj marca la medianoche.','The clock strikes midnight.'],['Una vieja fotografía les dio la primera pista.','An old photograph gave you the first clue.'],['La luna ilumina su siguiente caso.','The moon lights up your next case.'],['Hoy investigan un rumor que nadie logra explicar.','Today you investigate a rumor nobody can explain.'],['Su cuaderno tiene un misterio nuevo.','Your notebook has a new mystery.']];
 $('#main').innerHTML=lifeHeading(ghost?'Detectives del más allá':'Duelo de varitas',ghost?'Ghost detectives':'Wand duel',ghost?'Cada uno responde por su cuenta. Cada acierto gana 1 JJ.':'El ritmo acelera cada cuatro flechas. Tres errores terminan el duelo.',ghost?'Each player answers independently. Each correct answer earns 1 JJ.':'The rhythm speeds up every four arrows. Three mistakes end the duel.')+`<div class="duo-layout ${ghost?'with-guide':''}"><section class="game-panel duo-stage"><div id="duo-body"></div><p id="duo-error" class="duo-error" role="status"></p>${jjButton('duo-refresh','Actualizar sala','Refresh room','btn secondary')}</section><aside id="ghost-guide"></aside></div>`;
 function valid(){return !stopped&&v===state.version&&Boolean(state.profile);}
 function ms(){return Date.now()+offset-Date.parse(data?.start);}
 function accept(result,started){if(!valid()||(data&&Date.parse(result.now)<Date.parse(data.now)))return;offset=Date.parse(result.now)-(started+Date.now())/2;data=result;joined=data.members.some(m=>m.mine);if(lastRound!==data.round){lastRound=data.round;sent.clear();lastBeat=-99;}error='';}
 function name(id){return esc(data?.players?.find(p=>p.id===id)?.name||LIFE.profiles.find(p=>p.id===id)?.display_name||'J & J');}
 function render(){if(!valid())return;const key=JSON.stringify([data?{...data,now:null}:null,busy,error,UniverseI18n.language]);if(key===lastRender)return;lastRender=key;const active=data?.status==='active',finished=data?.status==='finished',mine=data?.members.find(m=>m.mine),types=data?.types||[];
 const memberHTML=`<div class="duo-status">${['julisa','jesus'].map(h=>{const member=data?.members.find(m=>m.id===LIFE.profiles.find(p=>p.handle===h)?.id||m.name===names[h]);return `<div class="duo-person">${esc(names[h])} · ${member?(member.ready||active?bi('Listo','Ready'):bi('En la sala','In room')):bi('Sin unirse','Not joined')}</div>`;}).join('')}</div>`;
 let body='';
 if(active&&ghost)body=`<p id="duo-countdown" aria-live="polite"></p><div class="ghost-art" aria-hidden="true">👻</div><p class="hint">${bi(...scenes[data.scene||0])}</p><p class="ghost-story">${bi(esc(data.story.es),esc(data.story.en))}</p><div class="ghost-clue"><strong>${bi('La pista','The clue')}</strong><p>${bi(esc(data.story.clue_es),esc(data.story.clue_en))}</p></div><div class="ghost-options">${(data.options||types.map(t=>t.id)).map(id=>{const t=types.find(t=>t.id===id);return t?`<button class="btn secondary" data-guess="${id}">${bi(esc(t.es),esc(t.en))}</button>`:'';}).join('')}</div><p>${data.inputs.length}/2 ${bi('respuestas recibidas. No se revelan hasta terminar.','answers received. Hidden until the round ends.')}</p>`;
 else if(active)body=`<p id="duo-countdown"></p><div class="duo-status">${data.players.map(p=>{const stats=data.stats?.find(s=>s.user===p.id);return `<span>${esc(p.name)}: ${stats?.mistakes||0}/3 ${bi('errores','mistakes')}</span>`;}).join('')}</div><div class="wand-sequence" id="wand-sequence" aria-hidden="true"></div><div class="wand-cue" id="wand-cue">✦</div><p id="wand-progress"></p><progress id="wand-time" max="1200" value="0" style="width:100%"></progress><div class="wand-pad">${arrowSymbols.map((a,i)=>`<button class="btn secondary" data-direction="${i}" aria-label="${say(['Arriba','Izquierda','Abajo','Derecha'][i],['Up','Left','Down','Right'][i])}">${a}</button>`).join('')}</div><p id="wand-feedback" class="wand-feedback" role="status"></p><p>${bi('Pulsa la flecha antes de que se llene la barra. Equivocarse u omitirla cuenta como un error.','Press the arrow before the bar fills. A wrong or missed arrow counts as a mistake.')}</p>`;
 else if(finished){const correct=data.inputs.filter(x=>x.correct).map(x=>x.user);const answer=types.find(t=>t.id===data.story?.answer);body=`<div class="duo-result"><div class="ghost-art">${ghost?'👻':'🪄'}</div><h2>${ghost?(correct.length?bi('¡Caso resuelto!','Case solved!'):bi('Este misterio se les escapó','This mystery got away')):data.winner?`${name(data.winner)} ${bi('gana el duelo','wins the duel')}`:bi('¡Empate!','A tie!')}</h2>${ghost?`<p>${bi('Era:','It was:')} ${answer?bi(esc(answer.es),esc(answer.en)):''}</p>`:''}${data.players.map(p=>{const stats=data.stats?.find(s=>s.user===p.id),reward=data.rewards?.includes(p.id);return `<p><strong translate="no">${esc(p.name)}</strong> · ${ghost?(correct.includes(p.id)?bi('Acertó','Correct'):bi('No acertó','Incorrect')):`${stats?.mistakes||0}/3 ${bi('errores','mistakes')}`} · ${reward?'<strong>+1 JJ ✓</strong>':'0 JJ'}</p>`;}).join('')}<p>${bi('Ambos deben unirse a la revancha.','Both players must join the rematch.')}</p></div>`;}
 else body=`<div class="ghost-art">${ghost?'👻':'🪄'}</div><h2>${bi('Los dos hacen falta','It takes both of you')}</h2><p>${data?.status==='abandoned'?bi('Partida cancelada. Vuelvan a unirse; no se asignaron premios.','Round cancelled. Join again; no rewards were assigned.'):bi('Abran este apartado en ambos dispositivos y pulsen Unirme.','Open this section on both devices and press Join.')}</p>`;
 $('#duo-body').innerHTML=memberHTML+body+`<div class="row" style="justify-content:center;margin-top:20px">${!active?`<button id="duo-join" class="btn" ${busy||mine?.ready?'disabled':''}>${mine?.ready?bi('Esperando al otro perfil…','Waiting for the other profile…'):bi(finished?'Revancha':'Unirme',finished?'Rematch':'Join')}</button>`:''}${mine?jjButton('duo-leave','Salir de la sala','Leave room','btn secondary'):''}</div>${state.demo?`<p>${bi('Necesitan sus cuentas reales y el SQL 10.','Real accounts and SQL 10 are required.')}</p>`:''}`;
 if(ghost)$('#ghost-guide').innerHTML=`<details class="game-panel" open><summary><strong>${bi('Guía de fantasmas','Ghost guide')}</strong></summary><p class="hint">${bi('Son las reglas de este juego. Compara el comportamiento con las pistas.','These are the rules of this game. Match each behavior with the clues.')}</p>${types.map(t=>`<section class="ghost-entry"><h3>${bi(esc(t.es),esc(t.en))}</h3><p>${bi(esc(t.description_es),esc(t.description_en))}</p></section>`).join('')}</details>`;
 if($('#duo-join'))$('#duo-join').onclick=()=>action('join');if($('#duo-leave'))$('#duo-leave').onclick=()=>action('leave');document.querySelectorAll('[data-guess]').forEach(b=>b.onclick=()=>action('guess',{p_round:data.round,p_answer:+b.dataset.guess}));document.querySelectorAll('[data-direction]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();tap(+b.dataset.direction);};b.onclick=e=>{if(e.detail===0)tap(+b.dataset.direction);};});$('#duo-error').textContent=error;lastBeat=-99;tick();
 }
 async function action(action,extra={},quiet=false){if(!valid())return;if(state.demo){if(!quiet)ensureLive();render();return;}if(busy||(quiet&&polling))return;if(quiet)polling=true;else busy=true;const started=Date.now();try{accept(await gameRpc('duo_action_v6',{p_kind:kind,p_session:session,p_action:action,...extra}),started);}catch(e){if(valid())error=gameErrorText(e);console.warn('Shared game',action,e);}finally{if(quiet)polling=false;else busy=false;render();}}
 async function tap(direction){if(!valid()||ghost||!joined||data?.status!=='active')return;const n=wandBeatAt(ms());if(n<0||n>=240||sent.has(n))return;sent.add(n);const round=data.round,started=Date.now();if($('#wand-feedback'))$('#wand-feedback').textContent=direction===data.sequence[n]?say('¡Bien!','Nice!'):say('Flecha incorrecta','Wrong arrow');try{accept(await gameRpc('duo_action_v6',{p_kind:kind,p_session:session,p_action:'tap',p_round:round,p_beat:n,p_answer:direction}),started);render();}catch(e){if(valid()){error=gameErrorText(e);$('#duo-error').textContent=error;}}}
 function tick(){if(!valid()||data?.status!=='active')return;const elapsed=ms(),count=$('#duo-countdown');const text=elapsed<0?`${say('Comenzamos en','Starting in')} ${Math.ceil(-elapsed/1000)}…`:ghost?say('Elige tu respuesta · hasta 5 minutos','Choose your answer · up to 5 minutes'):say('Tres errores terminan el duelo','Three mistakes end the duel');if(count&&count.textContent!==text)count.textContent=text;
 if(ghost){document.querySelectorAll('[data-guess]').forEach(b=>b.disabled=elapsed<0||!joined||busy||data.inputs.some(i=>i.user===state.profile.id));return;}const n=wandBeatAt(elapsed);if($('#wand-time')){$('#wand-time').max=wandBeatDuration(Math.max(0,n));$('#wand-time').value=n<0?0:elapsed-wandBeatStart(n);}document.querySelectorAll('[data-direction]').forEach(b=>b.disabled=n<0||n>=240||!joined);if(lastBeat!==n){lastBeat=n;$('#wand-cue').textContent=n<0?'✦':n>=240?'✨':arrowSymbols[data.sequence[n]];$('#wand-progress').textContent=n<0?say('Prepara tu varita','Ready your wand'):n>=240?say('Consultando resultado…','Checking result…'):`${say('Flecha','Arrow')} ${n+1} · ${(wandBeatDuration(n)/1000).toFixed(2)} s`;$('#wand-sequence').innerHTML=data.sequence.slice(Math.max(n,0),Math.max(n,0)+5).map((x,i)=>`<span class="${i===0&&n>=0?'current':''}">${arrowSymbols[x]}</span>`).join('');}}
 const key=e=>{const i={ArrowUp:0,ArrowLeft:1,ArrowDown:2,ArrowRight:3}[e.key];if(i!==undefined&&!e.repeat&&!$('#modal').open){e.preventDefault();tap(i);}};
 const leave=()=>{if(joined&&!state.demo)gameRpc('duo_action_v6',{p_kind:kind,p_session:session,p_action:'leave'}).catch(()=>{});};const visibility=()=>{if(document.hidden){leave();joined=false;}else action('ping',{},true);};const lang=()=>{lastRender='';render();};document.addEventListener('keydown',key);document.addEventListener('visibilitychange',visibility);window.addEventListener('universe-language',lang);window.addEventListener('pagehide',leave);$('#duo-refresh').onclick=()=>action('ping');const poll=setInterval(()=>{if(!document.hidden)action('ping',{},true);},700),clock=setInterval(tick,50);
 JJ.cleanups.push(()=>{leave();stopped=true;clearInterval(poll);clearInterval(clock);document.removeEventListener('keydown',key);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('universe-language',lang);window.removeEventListener('pagehide',leave);});await action('ping',{},true);render();
}
