'use strict';
menus.push(['gifts','🎁','Nueve regalos para ti']);
const giftIdeas=[['Nuestro primer capítulo','Our first chapter','Un cómic de cómo nos conocimos.','A comic about how we met.'],['Lo que siento contigo','How I feel with you','Una carta con tus propias palabras.','A letter in your own words.'],['Una canción para ti','A song for you','Una canción creada por nosotros.','A song created by us.'],['Un poema con mi voz','A poem in my voice','Tu poema narrado bajo las estrellas.','Your narrated poem beneath the stars.'],['Nuestro futuro juntos','Our future together','Una máquina del tiempo con nuestros sueños.','A time machine with our dreams.'],['Pequeños momentos','Little moments','Un álbum o collage de sus recuerdos.','An album or collage of your memories.'],['Nueve cosas de ti','Nine things about you','Nueve detalles que te encantan de ella.','Nine things you love about her.'],['Nuestra próxima aventura','Our next adventure','Una invitación a una cita juntos.','An invitation to a date together.'],['Antes de la última pieza','Before the last piece','Un mensaje de voz para escuchar contigo.','A voice message to listen to with you.']];
function giftError(e){const codes={EDIT_LOCKED:['Los regalos ya están abiertos para ella. No se pueden editar.','The gifts have been released and can no longer be edited.'],NINE_READY:['Prepara y marca listos los nueve regalos.','Prepare and mark all nine gifts as ready.'],NOT_SOLVED:['Espera a que Julissa complete el puzle.','Wait for Julissa to finish the puzzle.'],BOTH_LANGUAGES:['Completa título y texto en ambos idiomas.','Complete the title and text in both languages.'],STALE_BOARD:['El tablero cambió. Actualiza y vuelve a intentarlo.','The board changed. Refresh and try again.']};const key=Object.keys(codes).find(k=>e?.message?.includes(k));return key?say(...codes[key]):say('No se pudo confirmar. Pulsa Actualizar. Comprueba la conexión y el SQL 17.','Could not confirm. Press Refresh. Check your connection and SQL 17.')+' '+String(e?.code||'');}
function giftSpotify(value){if(!value.trim())return '';const u=new URL(value);if(u.protocol!=='https:'||u.hostname!=='open.spotify.com')throw Error('Spotify: https://open.spotify.com/…');const match=u.pathname.match(/^\/(?:intl-[a-z]+\/)?(track|playlist)\/([A-Za-z0-9]{22})\/?$/);if(!match)throw Error(say('Pega un enlace de canción o playlist de Spotify.','Paste a Spotify song or playlist link.'));return 'https://open.spotify.com/'+match[1]+'/'+match[2];}
async function giftsPage(v){
 const owner=state.profile.handle==='jesus',uid=state.profile.id;let data=null,busy=false,stopped=false,selected=null,last='',inFlight=Promise.resolve(),showFinal=false;
 const valid=()=>!stopped&&state.version===v&&state.profile?.id===uid;
 $('#main').innerHTML=`<div class="gifts-space"><header class="gifts-hero"><span class="eyebrow">JESÚS & JULISSA · ♡</span><h1>${bi('Nueve regalos para ti','Nine gifts for you')}</h1><p>${bi('Pequeños pedacitos de lo que somos. Una sorpresa para descubrir contigo.','Little pieces of us. A surprise to discover together.')}</p><span class="gift-stars" aria-hidden="true">✧ · ♡ · ✧</span></header><div id="gifts-room"></div><p id="gifts-status" role="status"></p>${jjButton('gifts-refresh','Actualizar','Refresh','btn secondary')}</div>`;
 function render(){if(!valid()||!data)return;const key=JSON.stringify([data,busy,selected,UniverseI18n.language]);if(key===last)return;last=key;const ready=data.gifts.filter(g=>g.ready).length;let html='';
  if(owner)html+=`<section class="gift-control"><h2>${bi('Tu mesa de preparativos','Your preparation desk')}</h2><p>${bi('Solo tú ves estos controles. Prepara los regalos antes de abrir la sorpresa. Después quedarán guardados sin cambios.','Only you see these controls. Prepare the gifts before opening the surprise. They will then be saved without further changes.')}</p><p>${ready}/9 ${bi('regalos listos','gifts ready')} · ${data.claimed.length}/9 ${bi('piezas reclamadas por Julissa','pieces claimed by Julissa')}</p>${!data.live?jjButton('gifts-publish','Abrir los nueve regalos para Julissa','Open the nine gifts for Julissa'):bi('La sorpresa ya está abierta para Julissa.','The surprise is open for Julissa.')}<p>${data.solved?bi('✓ Julissa completó el puzle.','✓ Julissa finished the puzzle.'):bi('La pregunta seguirá bloqueada hasta que ella arme el puzle y tú pulses el botón final.','The question stays locked until she solves the puzzle and you press the final button.')}</p>${data.solved&&!data.revealed?jjButton('gifts-release','Estoy listo: mostrar la pregunta ahora','I am ready: show the question now'):''}</section>`;
  if(!owner&&!data.live)html+=`<section class="gift-wait"><span>🎀</span><h2>${bi('Algo bonito se está preparando','Something lovely is being prepared')}</h2><p>${bi('Vuelve cuando Jesús te invite a abrirlo juntos.','Come back when Jesús invites you to open it together.')}</p></section>`;
  else{
   html+=`<p class="gift-progress">${data.claimed.length} / 9 · ${bi('pedacitos de nosotros','little pieces of us')}</p><div class="gift-grid">${data.gifts.map((g,i)=>`<article class="gift-box ${data.claimed.includes(g.id)?'gift-claimed':''}"><span class="gift-number">0${g.id}</span><div aria-hidden="true" class="gift-icon">${['✉','♡','♫','▷','♬','▧','✧','☀','🎀'][i]}</div><h2>${owner?bi(esc(g.title_es||giftIdeas[i][0]),esc(g.title_en||giftIdeas[i][1])):bi('Regalo '+g.id,'Gift '+g.id)}</h2><p>${owner?(g.ready?bi('Listo ✓','Ready ✓'):bi('Por preparar','To prepare')):data.claimed.includes(g.id)?bi('Pieza guardada ✓','Piece saved ✓'):bi('Hecho con cariño','Made with love')}</p><button class="btn secondary" data-gift-open="${g.id}">${owner?bi('Vista previa','Preview'):bi('Abrir regalo','Open gift')}</button>${owner&&!data.live?`<button class="text-button" data-gift-edit="${g.id}">${bi('Preparar / editar','Prepare / edit')}</button>`:''}</article>`).join('')}</div>`;
   if(data.claimed.length===9){html+=`<section class="gift-puzzle"><h2>${bi('Ahora, une nuestros pedacitos','Now, put our pieces together')}</h2><p>${bi('Toca dos piezas para intercambiarlas. No hay prisa ni tiempo límite.','Tap two pieces to swap them. There is no rush or time limit.')}</p><div class="gift-board">${data.board.map((tile,i)=>`<button class="gift-tile ${selected===i?'selected':''}" data-gift-tile="${i}" aria-label="${say('Pieza ','Piece ')+(i+1)}" aria-pressed="${selected===i}" style="background-position:${tile%3*50}% ${Math.floor(tile/3)*50}%" ${owner||busy||data.solved?'disabled':''}></button>`).join('')}</div><details><summary>${bi('Ver imagen completa','See the complete picture')}</summary><img src="assets/our-hands.jpg" alt="${say('Nuestras manos','Our hands')}"></details>${data.solved&&!data.revealed?`<div class="gift-wait"><h3>${bi('La última sorpresa está por llegar…','One last surprise is on its way…')}</h3><p>${bi('Mira a Jesús en la videollamada. Él abrirá este momento contigo.','Look at Jesús on your video call. He will open this moment with you.')}</p></div>`:''}</section>`;}
   if(data.question)html+=`<section class="gift-finale" role="status"><div aria-hidden="true">♡</div><p>${bi('Hay algo que quiero preguntarte…','There is something I want to ask you…')}</p><h2 translate="no">${esc(data.question[UniverseI18n.language]||data.question.en)}</h2><p>${bi('Te escucho. A tu tiempo, con tus palabras.','I am listening. In your own time, in your own words.')}</p></section>`;
  }
  $('#gifts-room').innerHTML=html;
  $('[id="gifts-publish"]')?.addEventListener('click',()=>{modal(`<h2>${bi('¿Todo listo para abrir la sorpresa?','Ready to open the surprise?')}</h2><p>${bi('Julissa podrá ver los regalos. Sus contenidos quedarán fijos, pero la pregunta final seguirá bloqueada hasta que tú la muestres.','Julissa will be able to open the gifts. Their contents will be locked, but the final question stays hidden until you reveal it.')}</p>${jjButton('gift-publish-confirm','Sí, abrir regalos','Yes, open gifts')}`);$('#gift-publish-confirm').onclick=async()=>{await send('publish');$('#modal').close();};});
  $('#gifts-release')?.addEventListener('click',()=>send('reveal'));
  document.querySelectorAll('[data-gift-open]').forEach(b=>b.onclick=async()=>{const id=+b.dataset.giftOpen;if(!owner&&!await send('open',{id}))return;showGift(data.gifts.find(g=>g.id===id));});
  document.querySelectorAll('[data-gift-edit]').forEach(b=>b.onclick=()=>editGift(data.gifts.find(g=>g.id===+b.dataset.giftEdit)));
  document.querySelectorAll('[data-gift-tile]').forEach(b=>b.onclick=()=>{const n=+b.dataset.giftTile;if(selected===null){selected=n;render();}else if(selected===n){selected=null;render();}else{const a=selected;selected=null;send('swap',{a,b:n,version:data.version});}});
 }
 async function send(action,payload={},quiet=false){if(!valid()||state.demo||(quiet&&busy))return false;while(busy){await inFlight;if(!valid())return false;}busy=true;let complete;inFlight=new Promise(resolve=>complete=resolve);try{const result=await gameRpc('jj_proposal',{p_action:action,p_data:payload});if(!valid())return false;showFinal=!!result.question&&!data?.question;data=result;$('#gifts-status').textContent='';return true;}catch(e){if(valid())$('#gifts-status').textContent=giftError(e);return false;}finally{busy=false;complete();if(valid()){render();if(showFinal){$('.gift-finale')?.scrollIntoView({behavior:'auto',block:'center'});showFinal=false;}}}}
 async function showGift(g){modal(`<div class="gift-letter"><div class="eyebrow">0${g.id} · J & J</div><h2>${bi(esc(g.title_es||giftIdeas[g.id-1][0]),esc(g.title_en||giftIdeas[g.id-1][1]))}</h2><div class="gift-body">${bi(esc(g.body_es||giftIdeas[g.id-1][2]),esc(g.body_en||giftIdeas[g.id-1][3]))}</div><div id="gift-media"></div>${g.spotify?`${jjButton('gift-spotify-play','Escuchar en el reproductor','Listen in the player')}<a href="${esc(g.spotify)}" target="_blank" rel="noopener noreferrer">${bi('Abrir en Spotify','Open in Spotify')}</a>`:''}<p>${owner?bi('Vista previa: no reclama piezas ni revela la pregunta.','Preview: does not claim pieces or reveal the question.'):bi('Cuando termines de disfrutar el regalo, guarda tu pieza.','When you have enjoyed the gift, save your piece.')}</p>${!owner?jjButton('gift-claim',data.claimed.includes(g.id)?'Pieza guardada ✓':'Ya lo vi: reclamar pieza',data.claimed.includes(g.id)?'Piece saved ✓':'I have seen it: claim piece'):''}</div>`);const generation=modalVersion;
  $('#gift-spotify-play')?.addEventListener('click',()=>{stopJJPlayer();showJJPlayer(g['title_'+UniverseI18n.language]);$('#jj-player-media').innerHTML=`<iframe title="Spotify" class="gift-spotify" src="https://open.spotify.com/embed/${esc(g.spotify.split('.com/')[1])}" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>`;$('#modal').close();});
  $('#gift-claim')?.addEventListener('click',async()=>{if(await send('claim',{id:g.id}))$('#modal').close();});
  if(g.path)try{const {data:url,error}=await db.storage.from('jj-gifts').createSignedUrl(g.path,3600);if(error)throw error;if(generation!==modalVersion)return;const el=document.createElement(g.media==='image'?'img':g.media);el.src=url.signedUrl;el.className='gift-media';if(g.media==='image')el.alt=g['title_'+UniverseI18n.language];else{el.controls=true;el.setAttribute('playsinline','');el.setAttribute('aria-label',g['title_'+UniverseI18n.language]);if(g.media==='video'){el.onplay=()=>{JJPlayer.audio?.pause();if($('#jj-player-media iframe'))stopJJPlayer();};$('#modal').addEventListener('close',()=>el.pause(),{once:true});}}$('#gift-media').append(el);}catch{if(generation===modalVersion)$('#gift-media').textContent=say('No se pudo cargar. Cierra y vuelve a abrir el regalo.','Could not load. Close and reopen the gift.');}
  await GiftExperience.mount(g,generation);
 }
 function editGift(g){let path=g.path,media=g.media;modal(`<h2>${bi('Preparar regalo','Prepare gift')} ${g.id}</h2><p>${bi(...giftIdeas[g.id-1].slice(2))}</p><form id="gift-form" class="stack"><label>Título · Español<input name="title_es" maxlength="120" value="${esc(g.title_es||giftIdeas[g.id-1][0])}" required></label><label>Title · English<input name="title_en" maxlength="120" value="${esc(g.title_en||giftIdeas[g.id-1][1])}" required></label><label>Texto · Español<textarea name="body_es" maxlength="5000" rows="6">${esc(g.body_es)}</textarea></label><label>Text · English<textarea name="body_en" maxlength="5000" rows="6">${esc(g.body_en)}</textarea></label>${jjButton('gift-translate','Traducir español → inglés','Translate Spanish → English','btn secondary')}<p class="hint">${bi('Al traducir, MyMemory recibe el texto. Revisa el resultado antes de guardarlo.','When translating, MyMemory receives the text. Review the result before saving.')}</p><label>${bi('Imagen, audio o video · máximo 50 MB','Picture, audio or video · up to 50 MB')}<input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/gif,audio/mpeg,audio/mp4,audio/wav,video/mp4,video/webm"></label><p>${bi('Puedes subir un cómic como imagen larga, un collage, un MP3 o un MP4. Para canciones y videos existentes, usa tu archivo original.','Upload a comic as one tall image, a collage, an MP3 or an MP4. For existing songs and videos, use your original file.')}</p>${g.path?`<label><input type="checkbox" name="remove"> ${bi('Quitar archivo del regalo','Remove file from gift')}</label>`:''}<label>${bi('Enlace de canción o playlist de Spotify (opcional)','Spotify song or playlist link (optional)')}<input name="spotify" type="url" value="${esc(g.spotify)}"></label>${GiftExperience.fields(g)}<label><input name="ready" type="checkbox" ${g.ready?'checked':''}> ${bi('Regalo listo en ambos idiomas','Gift ready in both languages')}</label><p id="gift-form-status" role="status"></p><button class="btn" type="submit">${bi('Guardar regalo','Save gift')}</button></form>`);
  const form=$('#gift-form');$('#gift-translate').type='button';$('#gift-translate').onclick=async()=>{const button=$('#gift-translate');button.disabled=true;form.querySelector('[type=submit]').disabled=true;busyModal(true);try{for(const k of ['title','body']){const text=form.elements[k+'_es'].value;if(text)form.elements[k+'_en'].value=await freeTranslate(text,'es','en');}$('#gift-form-status').textContent=say('Traducción lista. Revísala antes de guardar.','Translation ready. Review it before saving.');}catch{$('#gift-form-status').textContent=say('No se pudo traducir. Puedes escribir el inglés o reintentar.','Could not translate. Type the English version or retry.');}finally{button.disabled=false;form.querySelector('[type=submit]').disabled=false;busyModal(false);}};
  form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;busyModal(true);try{const f=new FormData(form),file=f.get('file');const spotify=giftSpotify(f.get('spotify'));if(file?.size){const types={'image/jpeg':'image','image/png':'image','image/webp':'image','image/gif':'image','audio/mpeg':'audio','audio/mp4':'audio','audio/wav':'audio','video/mp4':'video','video/webm':'video'};if(!types[file.type]||file.size>50*1024*1024)throw Error(say('Formato no compatible o archivo mayor de 50 MB.','Unsupported format or file larger than 50 MB.'));const newPath=uid+'/'+crypto.randomUUID();const {error}=await db.storage.from('jj-gifts').upload(newPath,file,{contentType:file.type,upsert:false});if(error)throw error;path=newPath;media=types[file.type];form.elements.file.value='';}else if(f.get('remove')){path='';media='';}const experience=await GiftExperience.collect(g,form,uid);const payload={id:g.id,path,media,spotify,experience,ready:!!f.get('ready')};for(const k of ['title_es','title_en','body_es','body_en'])payload[k]=f.get(k);const result=await gameRpc('jj_proposal',{p_action:'save',p_data:payload});if(valid()){data=result;render();}$('#modal').close();}catch(e){$('#gift-form-status').textContent=e.message||giftError(e);}finally{busyModal(false);button.disabled=false;}};
 }
 $('#gifts-refresh').onclick=()=>send('read');const language=()=>render();window.addEventListener('universe-language',language);const timer=setInterval(()=>{if(!document.hidden&&!$('#modal').open)send('read',{},true);},1500);JJ.cleanups.push(()=>{stopped=true;clearInterval(timer);window.removeEventListener('universe-language',language);});
 if(state.demo)$('#gifts-room').innerHTML=`<p>${bi('Inicia sesión con tu cuenta para preparar o abrir los regalos. Esta sorpresa guarda el progreso en Supabase y necesita SQL 17.','Sign in with your account to prepare or open gifts. This surprise saves progress in Supabase and requires SQL 17.')}</p>`;else await send('read');
}
const giftsNavigate=navigate;navigate=async function(page){if(page!=='gifts')return giftsNavigate(page);if(!state.profile)return;jjCleanup();clearTimers();state.page=page;const v=++state.version;shell();window.scrollTo(0,0);await giftsPage(v);};
