'use strict';
// Shared v5 features. All writes are checked again by Supabase.
menus.find(m=>m[0]==='flowers')[2]='Eventos';
menus.splice(1,0,['profile','☺','Perfiles']);
menus.push(['calendar','▦','Calendario'],['goals','✓','Metas'],['approvals','♧','Eliminaciones']);
const LIFE={profiles:[],dates:[],goals:[],month:new Date(new Date().getFullYear(),new Date().getMonth(),1),day:null};
function lifeError(e){console.error(e);toast(say('No se pudo guardar. Actualiza si el otro perfil hizo cambios y comprueba la actualización 08–09.','Could not save. Refresh if the other profile made changes and check update 08–09.'));}
function lifeHeading(es,en,subEs,subEn){return `<div class="page-heading"><div class="eyebrow">JULISSA & JESÚS</div><h1>${bi(es,en)}</h1><p>${bi(subEs,subEn)}</p></div>`;}
async function lifeRows(table){if(state.demo)return table==='profiles'?Object.entries(names).map(([handle,display_name])=>({id:'demo-'+handle,handle,display_name,avatar_icon:handle==='julisa'?'🦋':'🌙'})):[];const {data,error}=await db.from(table).select('*');if(error)throw error;return data;}
async function paintAvatars(){const user=state.profile;if(!user)return;try{const rows=await lifeRows('profiles');if(state.profile?.id!==user.id)return;LIFE.profiles=rows;cleanupDetachedMedia();for(const p of rows){for(const el of document.querySelectorAll(`.avatar.${p.handle}`)){el.textContent=p.avatar_icon||'♡';if(p.avatar_path){const url=await mediaUrl(p.avatar_path);if(el.isConnected&&state.profile?.id===user.id){const img=document.createElement('img');img.src=url;img.alt=p.display_name;el.replaceChildren(img);}}}}}catch(e){console.warn('Profile photo unavailable',e);}}
const lifeNavigate=navigate;
navigate=async function(page){if(!state.profile)return;if(!['profile','calendar','goals','approvals'].includes(page)){await lifeNavigate(page);if(state.page===page)paintAvatars();return;}
 jjCleanup();clearTimers();state.page=page;const v=++state.version;shell();window.scrollTo(0,0);
 try{await ({profile:profilePage,calendar:calendarPage,goals:goalsPage,approvals:approvalsPage}[page])(v);if(v===state.version)paintAvatars();}catch(e){if(v===state.version){$('#main').innerHTML=lifeHeading('Falta conectar la actualización','Connect the update','Ejecuta los archivos 08 y 09 en Supabase y vuelve a abrir este menú.','Run files 08 and 09 in Supabase, then reopen this menu.');}console.error(e);}
};
async function profilePage(v){const rows=await lifeRows('profiles');if(v!==state.version)return;LIFE.profiles=rows;const me=rows.find(p=>p.id===state.profile.id)||state.profile;
 $('#main').innerHTML=lifeHeading('Nuestros perfiles','Our profiles','Dos personas, un pequeño universo. Cada uno elige su propia imagen.','Two people, one little universe. Each of you chooses your own picture.')+`<div class="profile-pair">${rows.map(p=>`<article class="game-panel"><span class="avatar profile-large ${p.handle}">${esc(p.avatar_icon||'♡')}</span><h2 translate="no">${esc(p.display_name)}</h2><p>${bi(p.id===me.id?'Este eres tú':'Tu persona favorita',p.id===me.id?'This is you':'Your favorite person')}</p></article>`).join('')}</div><form id="profile-form" class="game-panel stack"><h2>${bi('Tu imagen','Your picture')}</h2><label>${bi('Elige un icono','Choose an icon')}<select name="icon" translate="no">${['♡','🌙','🌻','🎃','🦋','⭐','🐱','🐻','🪄','👻','🎵','🌹'].map(x=>`<option ${x===me.avatar_icon?'selected':''}>${x}</option>`).join('')}</select></label><label>${bi('O sube una foto · JPG, PNG, WebP o GIF · hasta 10 MB','Or upload a photo · JPG, PNG, WebP or GIF · up to 10 MB')}<input type="file" name="photo" accept="image/jpeg,image/png,image/webp,image/gif"></label><label class="row"><input type="checkbox" name="remove">${bi('Quitar mi foto y usar el icono','Remove my photo and use the icon')}</label><p id="profile-error" class="error"></p><button class="btn">${bi('Guardar perfil','Save profile')}</button></form><section class="game-panel translation-settings"><h2>${bi('Nuestros idiomas','Our languages')}</h2><p>${bi('La traducción gratuita usa MyMemory. Envía solo títulos y textos a ese servicio externo, nunca fotos, audios ni contraseñas. Tiene límites diarios y puede cometer errores.','Free translation uses MyMemory. It sends only titles and texts to that external service, never pictures, audio or passwords. It has daily limits and may make mistakes.')}</p><label class="row"><input id="auto-translate" type="checkbox" ${localStorage.getItem('jj-translate')!=='off'?'checked':''}>${bi('Traducir automáticamente en este dispositivo','Translate automatically on this device')}</label><p class="hint">${bi('El original siempre se conserva. Puedes corregir el idioma original al editar tu publicación.','The original is always preserved. You can correct the original language when editing your post.')}</p></section>`;
 $('#auto-translate').onchange=e=>{localStorage.setItem('jj-translate',e.target.checked?'on':'off');};
 $('#profile-form').onsubmit=async e=>{e.preventDefault();if(!ensureLive())return;const f=new FormData(e.target),b=$('button',e.target);b.disabled=true;try{const uploaded=[];const path=await upload(f.get('photo'),'image',uploaded)|| (f.has('remove')?null:me.avatar_path||null);await rpc('jj_profile',{p_icon:f.get('icon'),p_path:path});toast(say('Perfil guardado','Profile saved'));await navigate('profile');}catch(err){$('#profile-error').textContent=say('No se pudo confirmar el guardado. Puedes reintentar.','Could not confirm the save. You can try again.');}finally{b.disabled=false;}};
}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function dateMatches(row,key){return row.annual?row.event_date.slice(5)===key.slice(5)&&key>=row.event_date:row.event_date===key;}
function sharedForm(kind,row,date){const isDate=kind==='date',id=row?.id||crypto.randomUUID();modal(`<h2>${bi(row?'Editar':'Añadir',row?'Edit':'Add')} ${bi(isDate?'fecha importante':'meta',isDate?'important date':'goal')}</h2><form id="shared-form" class="stack"><label>${bi('Título','Title')}<input name="title" value="${esc(row?.title||'')}" required maxlength="${isDate?120:200}"></label><label>${bi('Detalles','Details')}<textarea name="body" maxlength="3000">${esc(row?.body||'')}</textarea></label>${isDate?`<label>${bi('Fecha','Date')}<input name="date" type="date" value="${esc(row?.event_date||date||dateKey(new Date()))}" required></label><label class="row"><input name="annual" type="checkbox" ${row?.annual?'checked':''}>${bi('Repetir cada año (cumpleaños, aniversario)','Repeat every year (birthday, anniversary)')}</label>`:''}<p class="hint">${bi('Los dos podrán ver y editar esto.','Both of you can see and edit this.')}</p><p id="shared-error" class="error"></p><button class="btn">${bi('Guardar','Save')}</button>${row?`<button type="button" id="shared-delete" class="btn danger">${bi('Eliminar','Delete')}</button>`:''}</form>`);
 const mutate=async(action,data)=>{if(!ensureLive())return;busyModal(true);document.querySelectorAll('#shared-form button').forEach(b=>b.disabled=true);try{await rpc('jj_shared',{p_kind:kind,p_action:action,p_id:id,p_revision:row?.revision||1,p_data:data});$('#modal').close();await navigate(isDate?'calendar':'goals');}catch(err){$('#shared-error').textContent=say('No se pudo guardar. Si el otro perfil lo editó, cierra y actualiza antes de reintentar.','Could not save. If the other profile edited it, close and refresh before trying again.');}finally{busyModal(false);document.querySelectorAll('#shared-form button').forEach(b=>b.disabled=false);}};
 $('#shared-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);mutate(row?'save':'create',{title:f.get('title'),body:f.get('body'),date:f.get('date'),annual:f.has('annual')});};
 if(row)$('#shared-delete').onclick=()=>{if(confirm(say('¿Eliminar esta fecha o meta para los dos?','Delete this date or goal for both of you?')))mutate('delete',{});};
}
async function calendarPage(v){LIFE.dates=(await lifeRows('shared_dates')).map(r=>({...r,event_date:r.event_date.slice(0,10)}));if(v!==state.version)return;const month=LIFE.month;const y=month.getFullYear(),m=month.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7;const today=dateKey(new Date());if(!LIFE.day)LIFE.day=today;
 $('#main').innerHTML=lifeHeading('Nuestro calendario','Our calendar','Cumpleaños, próximas citas y días que queremos recordar.','Birthdays, future dates and days we want to remember.')+`<div class="calendar-toolbar"><button class="btn secondary" id="previous-month" aria-label="${say('Mes anterior','Previous month')}">←</button><h2 translate="no">${month.toLocaleDateString(UniverseI18n.locale(),{month:'long',year:'numeric'})}</h2><button class="btn secondary" id="next-month" aria-label="${say('Mes siguiente','Next month')}">→</button></div><div class="row calendar-actions">${jjButton('calendar-today','Hoy','Today','btn secondary')}${jjButton('new-date','+ Añadir fecha','+ Add date')}${jjButton('refresh-calendar','Actualizar','Refresh','btn secondary')}</div><div class="calendar-scroll"><div class="calendar-week">${Array.from({length:7},(_,i)=>`<span translate="no">${new Date(2026,8,21+i).toLocaleDateString(UniverseI18n.locale(),{weekday:'short'})}</span>`).join('')}</div><div class="calendar-grid">${Array.from({length:42},(_,i)=>{const d=new Date(y,m,1-offset+i),key=dateKey(d),events=LIFE.dates.filter(r=>dateMatches(r,key));return `<button class="calendar-day ${d.getMonth()!==m?'outside':''} ${key===today?'today':''} ${key===LIFE.day?'selected':''}" data-day="${key}" aria-label="${esc(key+' · '+events.length+' '+say('eventos','events'))}" aria-pressed="${key===LIFE.day}"><strong>${d.getDate()}</strong>${events.slice(0,2).map(r=>`<span translate="no">${esc(r.title)}</span>`).join('')}${events.length>2?`<small>+${events.length-2}</small>`:''}${events.length?'<i aria-hidden="true">●</i>':''}</button>`;}).join('')}</div></div><section id="day-agenda" class="game-panel"></section>`;
 const agenda=()=>{$('#day-agenda').innerHTML=`<h2 translate="no">${new Date(LIFE.day+'T12:00:00').toLocaleDateString(UniverseI18n.locale(),{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</h2>${LIFE.dates.filter(r=>dateMatches(r,LIFE.day)).map(r=>`<button class="agenda-item" data-date-edit="${r.id}"><strong translate="no">${esc(r.title)}</strong><span translate="no">${esc(r.body)}</span><small>${bi('De','By')} ${esc(LIFE.profiles.find(p=>p.id===r.author_id)?.display_name||'J & J')} · ${bi('Editar','Edit')}</small></button>`).join('')||`<p>${bi('Un día por escribir juntos.','A day for us to fill together.')}</p>`}${jjButton('add-this-day','+ Algo para este día','+ Something for this day','btn secondary')}`;$('#add-this-day').onclick=()=>sharedForm('date',null,LIFE.day);document.querySelectorAll('[data-date-edit]').forEach(b=>b.onclick=()=>sharedForm('date',LIFE.dates.find(r=>r.id===b.dataset.dateEdit)));};agenda();
 document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{LIFE.day=b.dataset.day;document.querySelectorAll('[data-day]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});agenda();});
 $('#previous-month').onclick=()=>{LIFE.month=new Date(y,m-1,1);navigate('calendar');};$('#next-month').onclick=()=>{LIFE.month=new Date(y,m+1,1);navigate('calendar');};$('#calendar-today').onclick=()=>{LIFE.month=new Date(new Date().getFullYear(),new Date().getMonth(),1);LIFE.day=today;navigate('calendar');};$('#new-date').onclick=()=>sharedForm('date',null,LIFE.day);$('#refresh-calendar').onclick=()=>navigate('calendar');
}
async function goalsPage(v){LIFE.goals=await lifeRows('shared_goals');if(v!==state.version)return;const rows=LIFE.goals.sort((a,b)=>Number(a.completed)-Number(b.completed)||b.created_at.localeCompare(a.created_at));$('#main').innerHTML=lifeHeading('Nuestros sueños, paso a paso','Our dreams, one step at a time','Lugares por conocer, cosas por hacer y una vida para compartir.','Places to discover, things to do and a life to share.')+`<div class="row calendar-actions">${jjButton('new-goal','+ Añadir meta','+ Add goal')}${jjButton('refresh-goals','Actualizar','Refresh','btn secondary')}<span>${rows.filter(r=>r.completed).length} / ${rows.length} ${bi('completadas','completed')}</span></div><div class="goals-list">${rows.map(r=>`<article class="goal ${r.completed?'complete':''}"><input type="checkbox" data-check-goal="${r.id}" ${r.completed?'checked':''} aria-label="${esc(say('Completar: ','Complete: ')+r.title)}"><div><h3 translate="no">${esc(r.title)}</h3><p translate="no">${esc(r.body)}</p><small>${bi('De','By')} ${esc(LIFE.profiles.find(p=>p.id===r.author_id)?.display_name||'J & J')}</small></div><button class="btn secondary" data-edit-goal="${r.id}">${bi('Editar','Edit')}</button></article>`).join('')||`<div class="empty"><span class="symbol">✦</span><h2>${bi('¿Cuál es nuestro primer sueño?','What is our first dream?')}</h2></div>`}</div>`;
 $('#new-goal').onclick=()=>sharedForm('goal');$('#refresh-goals').onclick=()=>navigate('goals');document.querySelectorAll('[data-edit-goal]').forEach(b=>b.onclick=()=>sharedForm('goal',rows.find(r=>r.id===b.dataset.editGoal)));
 document.querySelectorAll('[data-check-goal]').forEach(b=>b.onchange=async()=>{const r=rows.find(r=>r.id===b.dataset.checkGoal);b.disabled=true;try{await rpc('jj_shared',{p_kind:'goal',p_action:'check',p_id:r.id,p_revision:r.revision,p_data:{completed:b.checked}});await navigate('goals');}catch(e){b.checked=r.completed;b.disabled=false;lifeError(e);}});
}
async function deletionDialog(kind,row){if(!ensureLive())return;modal(`<h2>${bi('Decidirlo juntos','Decide together')}</h2><p translate="no">${esc(row.title)}</p><p>${bi('Esto enviará una solicitud. Solo se eliminará cuando el otro perfil también acepte. Al eliminar una canción se quitará de las playlists; los comentarios también se eliminan.','This sends a request. It will only be deleted when the other profile also agrees. Deleting a song removes it from playlists; comments are also deleted.')}</p>${jjButton('request-delete','Solicitar eliminación','Request deletion')}<p class="error" id="request-error"></p>`);$('#request-delete').onclick=async e=>{e.target.disabled=true;busyModal(true);try{await rpc('jj_delete',{p_kind:kind,p_id:row.id,p_revision:row.revision,p_action:'request'});$('#modal').close();await navigate('approvals');}catch(err){$('#request-error').textContent=say('No se pudo solicitar. Cierra y actualiza la publicación.','Could not request deletion. Close and refresh the post.');}finally{busyModal(false);e.target.disabled=false;}};}
async function approvalsPage(v){const rows=(await lifeRows('delete_requests')).filter(r=>r.status==='pending');if(v!==state.version)return;$('#main').innerHTML=lifeHeading('Lo decidimos juntos','We decide together','Revisa la publicación antes de aceptar. Cualquiera puede cancelar la solicitud.','Review the post before agreeing. Either person can cancel a request.')+`${jjButton('refresh-approvals','Actualizar solicitudes','Refresh requests','btn secondary')}<div class="goals-list">${rows.map(r=>`<article class="game-panel"><h3 translate="no">${esc(r.title)}</h3><p>${bi('Solicitado por','Requested by')} ${esc(LIFE.profiles.find(p=>p.id===r.requested_by)?.display_name||'J & J')}</p><div class="row"><button class="btn secondary" data-review="${r.id}">${bi('Ver contenido','View content')}</button>${r.requested_by!==state.profile.id?`<button class="btn danger" data-approve="${r.id}">${bi('Yo también acepto eliminar','I also agree to delete')}</button>`:`<span>${bi('Esperando a tu persona favorita','Waiting for your favorite person')}</span>`}<button class="btn secondary" data-cancel-request="${r.id}">${bi('Cancelar solicitud','Cancel request')}</button></div></article>`).join('')||`<div class="empty"><h2>${bi('Nada pendiente','Nothing pending')}</h2><p>${bi('Sus recuerdos están a salvo.','Your memories are safe.')}</p></div>`}</div>`;
 $('#refresh-approvals').onclick=()=>navigate('approvals');const getRow=async r=>{const {data,error}=await db.from(r.kind==='post'?'posts':'playlists').select(r.kind==='post'?'*,profiles(display_name)':'*,playlist_tracks(song_id,position),playlist_spotify_tracks(track_id,title,position)').eq('id',r.target_id).single();if(error)throw error;return data;};
 document.querySelectorAll('[data-review]').forEach(b=>b.onclick=async()=>{try{const r=rows.find(x=>x.id===b.dataset.review),p=await getRow(r);if(r.kind==='post')await openPost(p);else await listenPlaylist(p);}catch(e){lifeError(e);}});
 for(const [selector,action,key] of [['[data-approve]','approve','approve'],['[data-cancel-request]','cancel','cancelRequest']])document.querySelectorAll(selector).forEach(b=>b.onclick=async()=>{const r=rows.find(x=>x.id===b.dataset[key]);if(action==='approve'&&!confirm(say('¿Confirmas eliminar definitivamente este contenido para los dos?','Confirm permanent deletion of this content for both of you?')))return;b.disabled=true;try{await rpc('jj_delete',{p_kind:r.kind,p_id:r.target_id,p_revision:r.revision,p_action:action});await navigate('approvals');}catch(e){b.disabled=false;lifeError(e);}});
}
const weeklyMissionPage=missionPage;
missionPage=async function(v){await weeklyMissionPage(v);if(v!==state.version)return;const d=JJ.dashboard;const defs=[['visit','Entrar hoy','Visit today'],['letter','Enviar una cartita','Send a letter'],['comment','Dejar un comentario','Leave a comment'],['game','Completar un juego','Finish a game'],['together','Una tarjeta o fantasma juntos','A card or ghost together']];const target=$('.mission-grid');target.insertAdjacentHTML('beforebegin',`<h2>${bi('Cada día contigo','Every day with you')}</h2><p>${bi('Se renuevan a medianoche de Matamoros. +1 JJ por misión; tus monedas permanecen.','Resets at midnight in Matamoros. +1 JJ per mission; your coins stay.')} ${d.day_end?jjDate(d.day_end):''}</p><div class="mission-grid daily-grid">${defs.map(([id,es,en])=>{const m=d.daily?.find(x=>x.id===id)||{progress:0,claimed:false};return `<article class="mission ${m.claimed?'complete':''}"><span>${m.claimed?'✓':'☀'}</span><div><h3>${bi(es,en)}</h3><progress value="${Math.min(m.progress,1)}" max="1"></progress><p>${Math.min(m.progress,1)} / 1 · +1 JJ</p></div></article>`;}).join('')}</div><h2>${bi('Esta semana','This week')}</h2>`);
 const timer=setInterval(()=>{if(state.page==='missions'&&!document.hidden&&!$('#modal').open)navigate('missions');},60000);JJ.cleanups.push(()=>clearInterval(timer));};
window.addEventListener('universe-language',()=>{if(state.profile&&state.page==='calendar'&&!$('#modal').open)navigate(state.page);});

let mediaCleaning=false;
async function cleanupDetachedMedia(){if(mediaCleaning||state.demo||!state.profile)return;mediaCleaning=true;const user=state.profile.id;try{const paths=await rpc('jj_cleanup');if(!paths.length||state.profile?.id!==user)return;const {error}=await db.storage.from('universe').remove(paths);if(error)throw error;if(state.profile?.id===user)await rpc('jj_cleanup',{p_done:paths});}catch(e){console.warn('Media cleanup will retry on next visit',e);}finally{mediaCleaning=false;}}
