'use strict';
// This surface is outside #app and #modal: section changes never destroy playback.
const JJPlayer={queue:[],index:0,request:0,audio:null,owner:null};
const playerDock=document.createElement('section');playerDock.id='jj-player';playerDock.hidden=true;
playerDock.innerHTML=`<div class="player-heading"><strong id="jj-player-title" translate="no"></strong><button id="jj-player-stop" class="text-button">${bi('Detener y cerrar','Stop and close')} ×</button></div><div id="jj-player-media"></div><div id="jj-player-queue" class="row"></div><p id="jj-player-status" class="hint" role="status"></p>`;
document.body.append(playerDock);
function stopJJPlayer(){JJPlayer.request++;JJPlayer.audio?.pause();JJPlayer.audio=null;JJPlayer.queue=[];JJPlayer.owner=null;$('#jj-player-media').replaceChildren();playerDock.hidden=true;document.body.classList.remove('has-jj-player');if('mediaSession' in navigator)navigator.mediaSession.metadata=null;}
$('#jj-player-stop').onclick=stopJJPlayer;
function showJJPlayer(title){playerDock.hidden=false;document.body.classList.add('has-jj-player');JJPlayer.owner=state.profile?.id;$('#jj-player-title').textContent=title;$('#jj-player-status').textContent='';$('#jj-player-queue').innerHTML=JJPlayer.queue.length>1?`${jjButton('jj-player-prev','Anterior','Previous','text-button')}<span>${JJPlayer.index+1} / ${JJPlayer.queue.length}</span>${jjButton('jj-player-next','Siguiente','Next','text-button')}`:'';if($('#jj-player-prev'))$('#jj-player-prev').onclick=()=>playJJTrack(JJPlayer.index-1);if($('#jj-player-next'))$('#jj-player-next').onclick=()=>playJJTrack(JJPlayer.index+1);}
function attachJJAudio(audio,title){JJPlayer.audio?.pause();$('#jj-player-media').replaceChildren(audio);JJPlayer.audio=audio;audio.controls=true;audio.style.width='100%';showJJPlayer(title);if('mediaSession' in navigator){navigator.mediaSession.metadata=new MediaMetadata({title,artist:'Julissa & Jesús',album:'Nuestro universo'});navigator.mediaSession.setActionHandler('play',()=>audio.play().catch(()=>{}));navigator.mediaSession.setActionHandler('pause',()=>audio.pause());}}
// Adopt the actual playing element, preserving its time, buffer and gesture permission.
document.addEventListener('play',e=>{const audio=e.target;if(!(audio instanceof HTMLAudioElement)||playerDock.contains(audio)||!state.profile)return;const title=audio.getAttribute('aria-label')||audio.closest('article, #modal-body, .memory-player')?.querySelector('h2,h3,p')?.textContent||say('Nuestra música','Our music');JJPlayer.request++;JJPlayer.queue=[];const path=audio.dataset.media;const url=audio.currentSrc||audio.src;const placeholder=document.createElement('button');placeholder.className='text-button';placeholder.innerHTML=bi('♫ Escuchar en el reproductor','♫ Listen in the player');audio.replaceWith(placeholder);placeholder.onclick=()=>{if(JJPlayer.audio===audio){audio.play().catch(()=>{});playerDock.scrollIntoView({block:'nearest'});}else startJJQueue([{source:'local',title,audio_path:path,url}]);};attachJJAudio(audio,title);audio.play().catch(()=>{});},true);
async function startJJQueue(queue,index=0){JJPlayer.queue=queue;await playJJTrack(index);}
async function playJJTrack(index){if(!state.profile||!JJPlayer.queue.length)return;const queue=JJPlayer.queue;JJPlayer.index=(index+queue.length)%queue.length;const song=queue[JJPlayer.index],request=++JJPlayer.request,owner=state.profile.id;JJPlayer.audio?.pause();JJPlayer.audio=null;$('#jj-player-media').replaceChildren();showJJPlayer(song.title);if(song.source==='spotify'){$('#jj-player-media').innerHTML=spotifyEmbed(song.id);return;}try{const url=song.audio_path?await mediaUrl(song.audio_path):song.url;if(request!==JJPlayer.request||state.profile?.id!==owner)return;const audio=new Audio(url);audio.preload='metadata';attachJJAudio(audio,song.title);audio.onended=()=>{if(JJPlayer.index+1<JJPlayer.queue.length)playJJTrack(JJPlayer.index+1);};audio.onerror=()=>{$('#jj-player-status').textContent=say('No se pudo reproducir. Vuelve a elegir la canción.','Could not play. Select the song again.');};await audio.play().catch(()=>{$('#jj-player-status').textContent=say('Pulsa ▶ para escuchar.','Press ▶ to listen.');});}catch{if(request===JJPlayer.request)$('#jj-player-status').textContent=say('No se pudo cargar. Revisa tu conexión y vuelve a elegir la canción.','Could not load. Check your connection and select the song again.');}}
listenPlaylist=async function(playlist){const owner=state.profile?.id;try{const songs=await allSongs();if(owner!==state.profile?.id)return;const tracks=mixedPlaylistTracks(playlist,songs);modal(`<h2 translate="no">${esc(playlist.title)}</h2><p>${bi('Elige una canción. Puedes cerrar esta ventana y seguir recorriendo nuestro universo.','Choose a song. You can close this window and keep exploring our universe.')}</p><div class="playlist-queue">${tracks.map((s,i)=>`<button data-persistent-track="${i}" translate="no">▶ ${esc(s.title)}</button>`).join('')||bi('No quedan canciones disponibles.','No songs are available.')}</div>`);document.querySelectorAll('[data-persistent-track]').forEach(b=>b.onclick=()=>{startJJQueue(tracks,+b.dataset.persistentTrack);$('#modal').close();});}catch(e){lifeError(e);}};
const playerLogout=logout;logout=async function(){stopJJPlayer();return playerLogout();};
const playerShell=shell;shell=function(){if(JJPlayer.owner&&JJPlayer.owner!==state.profile?.id)stopJJPlayer();playerShell();};
