'use strict';
const JJPush={device:null,busy:false,pendingPage:null};
function pushDeviceId(){if(!JJPush.device){JJPush.device=localStorage.getItem('jj-push-device')||crypto.randomUUID();localStorage.setItem('jj-push-device',JJPush.device);}return JJPush.device;}
function pushSupported(){return isSecureContext&&'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;}
async function pushRegistration(){const result=await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error(say('Actualiza la página y vuelve a intentarlo.','Refresh the page and try again.'))),8000))]);return result;}
function pushKeyBytes(key){return Uint8Array.from(atob(key.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(key.length/4)*4,'=')),c=>c.charCodeAt(0));}
async function paintPushSettings(){const box=$('#jj-push-settings');if(!box||JJPush.busy)return;const owner=state.profile?.id;box.innerHTML=`<h3>${bi('Avisos en este teléfono','Notifications on this device')}</h3><p class="hint">${bi('Llegan incluso con la página cerrada. En iPhone: añade la página al inicio y ábrela desde ese icono (iOS 16.4 o posterior).','Receive alerts even when the page is closed. On iPhone: add the page to your Home Screen and open that icon (iOS 16.4 or later).')}</p><p class="hint">${bi('Al bloquear o dejar la aplicación, aparecerás sin conexión tras 1–2 minutos. Los avisos pueden tardar más según el teléfono y la red.','Locking or leaving the app marks you offline after 1–2 minutes. Delivery may take longer depending on your phone and network.')}</p>`;if(!pushSupported()){box.insertAdjacentHTML('beforeend',`<p>${bi('Este navegador no ofrece avisos. Prueba desde Chrome en Android o desde el icono de inicio en iPhone.','Notifications are unavailable in this browser. Try Chrome on Android or the Home Screen icon on iPhone.')}</p>`);return;}if(state.demo||!window.JJ_PUSH_CONFIG?.publicKey){box.insertAdjacentHTML('beforeend',`<p>${bi('Falta completar la configuración de avisos de la guía ACTUALIZAR-4-10-26.','Complete notification setup in ACTUALIZAR-4-10-26 first.')}</p>`);return;}let saved={};try{saved=await rpc('jj_push_device',{p_action:'read',p_id:pushDeviceId()});}catch{if(box.isConnected)box.insertAdjacentHTML('beforeend',`<p>${bi('No se pudo consultar la configuración. Revisa la conexión y el SQL 14.','Could not load settings. Check your connection and SQL 14.')}</p>`);return;}if(!box.isConnected||owner!==state.profile?.id)return;box.insertAdjacentHTML('beforeend',`<p>${saved.id?bi('Activados para este perfil en este dispositivo.','Enabled for this profile on this device.'):bi('Todavía no están activados aquí.','Not enabled here yet.')}</p><div class="push-options">${[['presence','Conexiones y desconexiones','Coming online and going offline'],['records','Récords y coronas','Records and crowns'],['content','Publicaciones, notitas y stickers','New content, notes and stickers']].map(([key,es,en])=>`<label><input type="checkbox" data-push-option="${key}" ${saved[key]!==false?'checked':''}>${bi(es,en)}</label>`).join('')}</div><div class="row">${jjButton('enable-push',saved.id?'Guardar preferencias':'Activar avisos',saved.id?'Save preferences':'Enable notifications')}${saved.id?jjButton('test-push','Enviar prueba','Send test','btn secondary')+jjButton('disable-push','Desactivar','Disable','text-button'):''}</div><p id="push-message" role="status"></p>`);$('#enable-push').onclick=()=>pushAction('save');if($('#disable-push'))$('#disable-push').onclick=()=>pushAction('delete');if($('#test-push'))$('#test-push').onclick=()=>pushAction('test');}
async function pushAction(action){if(JJPush.busy||!ensureLive())return;JJPush.busy=true;const owner=state.profile.id,box=$('#jj-push-settings'),message=$('#push-message');box?.querySelectorAll('button').forEach(b=>b.disabled=true);try{let data={};if(action==='save'){// Request permission immediately inside the user gesture (required by iOS).
 const permission=await Notification.requestPermission();if(permission!=='granted')throw Error(say('Permiso no concedido. Puedes cambiarlo en los ajustes de notificaciones del teléfono.','Permission was not granted. You can change it in your phone notification settings.'));
 const registration=await pushRegistration();let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:pushKeyBytes(window.JJ_PUSH_CONFIG.publicKey)});const json=subscription.toJSON();data={endpoint:json.endpoint,...json.keys,lang:UniverseI18n.language};box.querySelectorAll('[data-push-option]').forEach(c=>data[c.dataset.pushOption]=c.checked);
 }if(owner!==state.profile?.id)return;await rpc('jj_push_device',{p_action:action,p_id:pushDeviceId(),p_data:data});if(action==='delete'){const registration=await pushRegistration();await (await registration.pushManager.getSubscription())?.unsubscribe();}if(action==='test'){message.textContent=say('Prueba en cola. Debe llegar en aproximadamente un minuto cuando el envío esté configurado.','Test queued. It should arrive in about a minute once delivery is configured.');}else{JJPush.busy=false;await paintPushSettings();}}catch(error){if(message?.isConnected)message.textContent=error.message||say('No se pudo guardar. Vuelve a intentarlo.','Could not save. Please try again.');}finally{JJPush.busy=false;box?.querySelectorAll('button').forEach(b=>b.disabled=false);}}
const pushInbox=renderInbox;renderInbox=function(){pushInbox();const inbox=$('#jj-inbox');if(inbox){inbox.insertAdjacentHTML('afterend',document.getElementById('jj-push-settings')?'':'<section id="jj-push-settings" class="push-settings"></section>');if(!$('#jj-push-settings').children.length)paintPushSettings();}};
window.addEventListener('universe-language',()=>{if($('#jj-push-settings'))paintPushSettings();if(state.profile&&!state.demo&&JJPush.device)rpc('jj_push_device',{p_action:'language',p_id:JJPush.device,p_data:{lang:UniverseI18n.language}}).catch(()=>{});});
const pushLogout=logout;logout=async function(){if(state.profile&&!state.demo&&pushSupported()){try{await rpc('jj_push_device',{p_action:'delete',p_id:pushDeviceId()});const registration=await pushRegistration();await (await registration.pushManager.getSubscription())?.unsubscribe();}catch{toast(say('No se pudieron desactivar los avisos de este dispositivo. Desactívalos desde los ajustes del teléfono si lo vas a compartir.','Could not disable this device’s alerts. Disable them in phone settings if sharing this device.'));}}return pushLogout();};
if('serviceWorker' in navigator)navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='jj-push-open'&&menus.some(m=>m[0]===e.data.page)){if(!state.profile||modalBusy){JJPush.pendingPage=e.data.page;return;}if($('#modal').open)$('#modal').close();navigate(e.data.page);}});
const pushNavigate=navigate;let pushLanding=false;navigate=async function(page){if(state.profile){let wanted=JJPush.pendingPage;JJPush.pendingPage=null;if(!pushLanding){pushLanding=true;const url=new URL(location.href);wanted=wanted||url.searchParams.get('jj-open');url.searchParams.delete('jj-open');history.replaceState(history.state,'',url);}if(wanted&&menus.some(m=>m[0]===wanted)){page=wanted;if(typeof rememberRoute==='function')rememberRoute(historyRoute(page));}}return pushNavigate(page);};
