'use strict';
async function truthPage(v){
 let joined=false,busy=false,ended=false,last=null,networkError=false;
 $('#main').innerHTML=`<div class="page-heading"><div class="eyebrow">${bi('Lejos, pero jugando juntos','Far apart, playing together')}</div><h1>${bi('Verdad o reto','Truth or dare')}</h1><p>${bi('Entren los dos a esta sala. Las cartas se comparten y los turnos se alternan.','Both of you join this room. Cards are shared and turns alternate.')}</p></div>
 <section class="truth-lobby"><label class="check-line"><input id="flirty-choice" type="checkbox">${bi('También quiero tarjetas coquetas (opcional; solo si ambos aceptamos).','I also want flirty cards (optional; only if we both agree).')}</label><p class="hint">${bi('Siempre pueden omitir una tarjeta, sin explicación. Todo está pensado para una relación a distancia.','You can always skip a card, no explanation needed. Everything works for a long-distance relationship.')}</p><div class="row" style="margin-top:20px">${jjButton('join-truth','Unirme a la sala','Join the room')}${jjButton('leave-truth','Salir de la sala','Leave the room','btn secondary')}</div><p id="truth-connection" role="status"></p></section><div id="truth-live"></div>`;
 $('#leave-truth').disabled=true;
 function render(){if(v!==state.version||ended)return;const members=last?.members||[],connected=members.length===2&&!networkError&&joined;const yourTurn=last?.turn===state.profile.id;const card=last?.card;$('#join-truth').disabled=joined||busy;$('#leave-truth').disabled=!joined||busy;$('#flirty-choice').disabled=joined||busy;
  $('#truth-connection').innerHTML=networkError?bi('Sin conexión. No se puede sacar una tarjeta hasta recuperar la sala.','Offline. Cards are unavailable until the room reconnects.'):joined?`${members.length}/2 · `+members.map(m=>esc(m.name)).join(' + '):bi('Únete para esperar a la otra persona.','Join to wait for the other person.');
  $('#truth-live').innerHTML=`<div class="truth-card"><div class="eyebrow">${card?bi(card.kind==='truth'?'Verdad':'Reto',card.kind==='truth'?'Truth':'Dare'):bi('Nuestra próxima carta','Our next card')}</div><h2>${card?bi(esc(card.es),esc(card.en)):bi('Dos personas.<br>Una pequeña aventura.','Two people.<br>One little adventure.')}</h2><p>${!connected?bi('Esperando a que ambos estén en la sala…','Waiting for both of you to be in the room…'):yourTurn?bi('Es tu turno.','It is your turn.'):bi('Es el turno de la otra persona.','It is the other person’s turn.')}</p><div class="row">${card?`${jjButton('truth-done','Listo, cumplido','Done')}${jjButton('truth-skip','Omitir sin problema','Skip, no problem','btn secondary')}`:jjButton('truth-draw','Sacar una carta','Draw a card')}</div></div><p class="hint">${bi('La presencia se comprueba cada 8 segundos. Al salir o perder conexión, la sala se bloquea en un máximo de 45 segundos.','Presence is checked every 8 seconds. Leaving or disconnecting locks the room within 45 seconds.')}</p>`;
  for(const [id,action] of [['truth-draw','draw'],['truth-done','done'],['truth-skip','skip']])if($('#'+id)){$('#'+id).disabled=!connected||!yourTurn||busy;$('#'+id).onclick=()=>act(action);}
 }
 async function act(action){if(busy||ended)return;busy=true;render();try{
   if(state.demo){toast(say('La sala compartida necesita Supabase y los dos perfiles conectados.','The shared room needs Supabase and both profiles online.'));return;}
   const result=await rpc('truth_action',{p_action:action,p_flirty:$('#flirty-choice').checked});if(v!==state.version||ended)return;
   last=result;networkError=false;joined=result.members.some(m=>m.id===state.profile.id);$('#join-truth').disabled=joined;$('#leave-truth').disabled=!joined;$('#flirty-choice').disabled=joined;
 }catch(error){networkError=true;toast(say('No se pudo completar. Comprueba que los dos estén conectados y que sea tu turno.','Could not complete. Check that you are both online and that it is your turn.'));}finally{busy=false;render();}}
 $('#join-truth').onclick=()=>act('join');$('#leave-truth').onclick=()=>act('leave');
 const visibility=()=>{if(document.hidden&&joined&&!state.demo){joined=false;rpc('truth_action',{p_action:'leave'}).catch(()=>{});render();}};document.addEventListener('visibilitychange',visibility);
 const timer=setInterval(()=>{if(joined&&!document.hidden&&!ended&&!busy)act('ping');},8000);
 JJ.cleanups.push(()=>{ended=true;clearInterval(timer);document.removeEventListener('visibilitychange',visibility);if(joined&&!state.demo&&db)rpc('truth_action',{p_action:'leave'}).catch(()=>{});});render();
}
